affected_purls:
- pkg:npm/docker-compose-remote-api@0.1.1
- pkg:npm/docker-compose-remote-api@0.1.2
- pkg:npm/docker-compose-remote-api@0.1.3
- pkg:npm/docker-compose-remote-api@0.1.4
aliases:
- CVE-2020-7606
- GHSA-q6pj-jh94-5fpr
fixed_purl: []
references:
- id: 155244
  reference_id: ''
  url: https://snyk.io/vuln/SNYK-JS-DOCKERCOMPOSEREMOTEAPI-560125
- id: 155243
  reference_id: CVE-2020-7606
  url: https://nvd.nist.gov/vuln/detail/CVE-2020-7606
- id: 155245
  reference_id: GHSA-q6pj-jh94-5fpr
  url: https://github.com/advisories/GHSA-q6pj-jh94-5fpr
severities:
- id: 22343
  reference_id: 155245
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: CRITICAL
summary: OS Command Injection in docker-compose-remote-api
vulnerability_id: VCID-r28c-x4gj-aaab
weaknesses: []
