vulnerability_id: VCID-meae-62wh-aaam
aliases:
  - CVE-2021-27962
summary:
severities:
  - id: 606349
    reference_id: 928666
    scoring_system: cvssv3
    value: '6.8'
    scoring_elements: CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:C/C:H/I:N/A:N
  - id: 606348
    reference_id: 928665
    scoring_system: rhbs
    value: high
    scoring_elements:
  - id: 528085
    reference_id: 876858
    scoring_system: cvssv2
    value: '4.9'
    scoring_elements: AV:N/AC:M/Au:S/C:P/I:P/A:N
  - id: 528083
    reference_id: 876858
    scoring_system: cvssv3
    value: '7.1'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N
references:
  - id: 928666
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-27962.json
    reference_id:
  - id: 876854
    url: https://community.grafana.com
    reference_id:
  - id: 876855
    url: https://community.grafana.com/t/grafana-enterprise-6-7-6-7-3-10-and-7-4-5-security-update/44724
    reference_id:
  - id: 815325
    url: https://community.grafana.com/t/release-notes-v6-7-x/27119
    reference_id:
  - id: 876856
    url: https://grafana.com/blog/2021/03/18/grafana-6.7.6-7.3.10-and-7.4.5-released-with-important-security-fixes-for-grafana-enterprise/
    reference_id:
  - id: 876857
    url: https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-4-5/
    reference_id:
  - id: 876853
    url: http://www.openwall.com/lists/oss-security/2021/03/19/5
    reference_id:
  - id: 928665
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1937278
    reference_id: '1937278'
  - id: 837953
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:grafana:grafana:*:*:*:*:enterprise:*:*:*
    reference_id: cpe:2.3:a:grafana:grafana:*:*:*:*:enterprise:*:*:*
  - id: 876858
    url: https://nvd.nist.gov/vuln/detail/CVE-2021-27962
    reference_id: CVE-2021-27962
weaknesses: []
