vulnerability_id: VCID-rj2n-a8bp-aaad
aliases:
  - CVE-2021-41244
summary:
severities:
  - id: 46838
    reference_id: 171699
    scoring_system: cvssv3
    value: '9.1'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:H
  - id: 46837
    reference_id: 171698
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 562399
    reference_id: 899057
    scoring_system: cvssv2
    value: '6.5'
    scoring_elements: AV:N/AC:L/Au:S/C:P/I:P/A:P
  - id: 562397
    reference_id: 899057
    scoring_system: cvssv3
    value: '7.2'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H
references:
  - id: 171699
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-41244.json
    reference_id:
  - id: 899054
    url: https://github.com/grafana/grafana/security/advisories/GHSA-mpwp-42x6-4wmx
    reference_id:
  - id: 899055
    url: https://grafana.com/blog/2021/11/15/grafana-8.2.4-released-with-security-fixes/
    reference_id:
  - id: 899056
    url: https://security.netapp.com/advisory/ntap-20211223-0001/
    reference_id:
  - id: 899053
    url: http://www.openwall.com/lists/oss-security/2021/11/15/1
    reference_id:
  - id: 171698
    url: https://bugzilla.redhat.com/show_bug.cgi?id=2024730
    reference_id: 2024730
  - id: 728604
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:grafana:grafana:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:grafana:grafana:*:*:*:*:*:*:*:*
  - id: 899057
    url: https://nvd.nist.gov/vuln/detail/CVE-2021-41244
    reference_id: CVE-2021-41244
weaknesses: []
