vulnerability_id: VCID-bhfv-khhr-aaas
aliases:
  - CVE-2021-43813
summary:
severities:
  - id: 483493
    reference_id: 848843
    scoring_system: cvssv3
    value: '4.3'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N
  - id: 483491
    reference_id: 848841
    scoring_system: rhbs
    value: low
    scoring_elements:
  - id: 567937
    reference_id: 903237
    scoring_system: cvssv2
    value: '4.0'
    scoring_elements: AV:N/AC:L/Au:S/C:P/I:N/A:N
  - id: 567935
    reference_id: 903237
    scoring_system: cvssv3
    value: '4.3'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N
  - id: 338782
    reference_id: 746189
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 483492
    reference_id: 848842
    scoring_system: rhas
    value: Low
    scoring_elements:
  - id: 642081
    reference_id: 1182815
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 848843
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-43813.json
    reference_id:
  - id: 903230
    url: https://github.com/github/securitylab-vulnerabilities/commit/689fc5d9fd665be4d5bba200a6a433b532172d0f
    reference_id:
  - id: 903231
    url: https://github.com/grafana/grafana/commit/fd48aee61e4328aae8d5303a9efd045fa0ca308d
    reference_id:
  - id: 903232
    url: https://github.com/grafana/grafana/security/advisories/GHSA-c3q8-26ph-9g2q
    reference_id:
  - id: 903233
    url: https://grafana.com/blog/2021/12/10/grafana-8.3.2-and-7.5.12-released-with-moderate-severity-security-fix/
    reference_id:
  - id: 903234
    url: https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-5-12/
    reference_id:
  - id: 903235
    url: https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-3-2/
    reference_id:
  - id: 903236
    url: https://security.netapp.com/advisory/ntap-20220107-0006/
    reference_id:
  - id: 903179
    url: http://www.openwall.com/lists/oss-security/2021/12/10/4
    reference_id:
  - id: 848841
    url: https://bugzilla.redhat.com/show_bug.cgi?id=2031228
    reference_id: 2031228
  - id: 728604
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:grafana:grafana:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:grafana:grafana:*:*:*:*:*:*:*:*
  - id: 903237
    url: https://nvd.nist.gov/vuln/detail/CVE-2021-43813
    reference_id: CVE-2021-43813
  - id: 746189
    url: https://access.redhat.com/errata/RHSA-2022:0056
    reference_id: RHSA-2022:0056
  - id: 848842
    url: https://access.redhat.com/errata/RHSA-2022:1781
    reference_id: RHSA-2022:1781
  - id: 1182815
    url: https://access.redhat.com/errata/RHSA-2022:6024
    reference_id: RHSA-2022:6024
weaknesses: []
