vulnerability_id: VCID-xpya-myjw-aaas
aliases:
  - CVE-2021-28147
summary:
severities:
  - id: 606355
    reference_id: 928670
    scoring_system: cvssv3
    value: '6.8'
    scoring_elements: CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:C/C:H/I:N/A:N
  - id: 606354
    reference_id: 928669
    scoring_system: rhbs
    value: high
    scoring_elements:
  - id: 528457
    reference_id: 877160
    scoring_system: cvssv2
    value: '3.5'
    scoring_elements: AV:N/AC:M/Au:S/C:N/I:P/A:N
  - id: 528455
    reference_id: 877160
    scoring_system: cvssv3
    value: '6.5'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N
references:
  - id: 928670
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-28147.json
    reference_id:
  - id: 876855
    url: https://community.grafana.com/t/grafana-enterprise-6-7-6-7-3-10-and-7-4-5-security-update/44724
    reference_id:
  - id: 815325
    url: https://community.grafana.com/t/release-notes-v6-7-x/27119
    reference_id:
  - id: 876856
    url: https://grafana.com/blog/2021/03/18/grafana-6.7.6-7.3.10-and-7.4.5-released-with-important-security-fixes-for-grafana-enterprise/
    reference_id:
  - id: 877155
    url: https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-3-10/
    reference_id:
  - id: 876857
    url: https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-4-5/
    reference_id:
  - id: 877156
    url: https://grafana.com/products/enterprise/
    reference_id:
  - id: 877159
    url: https://security.netapp.com/advisory/ntap-20210430-0005/
    reference_id:
  - id: 877157
    url: https://www.openwall.com/lists/oss-security/2021/03/19/5
    reference_id:
  - id: 928669
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1938978
    reference_id: '1938978'
  - id: 837953
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:grafana:grafana:*:*:*:*:enterprise:*:*:*
    reference_id: cpe:2.3:a:grafana:grafana:*:*:*:*:enterprise:*:*:*
  - id: 877160
    url: https://nvd.nist.gov/vuln/detail/CVE-2021-28147
    reference_id: CVE-2021-28147
weaknesses: []
