package: pkg:deb/debian/modsecurity
versions:
  - purl: pkg:deb/debian/modsecurity@3.0.3-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
  - purl: pkg:deb/debian/modsecurity@3.0.3-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
  - purl: pkg:deb/debian/modsecurity@3.0.3-1%2Bdeb10u2?distro=sid
    affected_by_vulnerabilities:
      - VCID-aezv-zfjr-aaaf
      - VCID-xz6n-r2pv-aaan
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.3-1%2Bdeb10u2
    affected_by_vulnerabilities:
      - VCID-xz6n-r2pv-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/modsecurity@3.0.3-1%2Bdeb10u2?distro=sid
    affected_by_vulnerabilities:
      - VCID-aezv-zfjr-aaaf
      - VCID-xz6n-r2pv-aaan
      - VCID-yt3k-1axe-aaaa
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.4-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-xz6n-r2pv-aaan
  - purl: pkg:deb/debian/modsecurity@3.0.4-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-xz6n-r2pv-aaan
  - purl: pkg:deb/debian/modsecurity@3.0.4-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-aezv-zfjr-aaaf
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.4-2
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-xz6n-r2pv-aaan
  - purl: pkg:deb/debian/modsecurity@3.0.4-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-aezv-zfjr-aaaf
      - VCID-yt3k-1axe-aaaa
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-xz6n-r2pv-aaan
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.6-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-aezv-zfjr-aaaf
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.6-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-aezv-zfjr-aaaf
      - VCID-xz6n-r2pv-aaan
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.8-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.8-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-yt3k-1axe-aaaa
      - VCID-z6vn-zez1-aaaq
  - purl: pkg:deb/debian/modsecurity@3.0.8-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-1t8g-89au-aaaj
      - VCID-z6vn-zez1-aaaq
