affected_purls:
- pkg:pypi/esphome@1.10.1
- pkg:pypi/esphome@1.11.0
- pkg:pypi/esphome@1.11.0b1
- pkg:pypi/esphome@1.11.0b2
- pkg:pypi/esphome@1.11.0b3
- pkg:pypi/esphome@1.11.1
- pkg:pypi/esphome@1.11.2
- pkg:pypi/esphome@1.12.0
- pkg:pypi/esphome@1.12.0b1
- pkg:pypi/esphome@1.12.0b2
- pkg:pypi/esphome@1.12.0b3
- pkg:pypi/esphome@1.12.0b4
- pkg:pypi/esphome@1.12.1
- pkg:pypi/esphome@1.12.2
- pkg:pypi/esphome@1.13.0
- pkg:pypi/esphome@1.13.0b1
- pkg:pypi/esphome@1.13.0b2
- pkg:pypi/esphome@1.13.0b3
- pkg:pypi/esphome@1.13.0b4
- pkg:pypi/esphome@1.13.0b5
- pkg:pypi/esphome@1.13.0b6
- pkg:pypi/esphome@1.13.0b7
- pkg:pypi/esphome@1.13.1
- pkg:pypi/esphome@1.13.2
- pkg:pypi/esphome@1.13.3
- pkg:pypi/esphome@1.13.4
- pkg:pypi/esphome@1.13.5
- pkg:pypi/esphome@1.13.6
- pkg:pypi/esphome@1.14.0
- pkg:pypi/esphome@1.14.0b1
- pkg:pypi/esphome@1.14.0b2
- pkg:pypi/esphome@1.14.0b3
- pkg:pypi/esphome@1.14.0b4
- pkg:pypi/esphome@1.14.0b5
- pkg:pypi/esphome@1.14.1
- pkg:pypi/esphome@1.14.2
- pkg:pypi/esphome@1.14.3
- pkg:pypi/esphome@1.14.4
- pkg:pypi/esphome@1.14.5
- pkg:pypi/esphome@1.15.0
- pkg:pypi/esphome@1.15.0b1
- pkg:pypi/esphome@1.15.0b2
- pkg:pypi/esphome@1.15.0b3
- pkg:pypi/esphome@1.15.0b4
- pkg:pypi/esphome@1.15.1
- pkg:pypi/esphome@1.15.2
- pkg:pypi/esphome@1.15.3
- pkg:pypi/esphome@1.16.0
- pkg:pypi/esphome@1.16.0b1
- pkg:pypi/esphome@1.16.0b2
- pkg:pypi/esphome@1.16.0b3
- pkg:pypi/esphome@1.16.0b4
- pkg:pypi/esphome@1.16.0b5
- pkg:pypi/esphome@1.16.0b6
- pkg:pypi/esphome@1.16.0b7
- pkg:pypi/esphome@1.16.0b8
- pkg:pypi/esphome@1.16.1
- pkg:pypi/esphome@1.16.2
- pkg:pypi/esphome@1.17.0
- pkg:pypi/esphome@1.17.0b1
- pkg:pypi/esphome@1.17.1
- pkg:pypi/esphome@1.17.2
- pkg:pypi/esphome@1.18.0
- pkg:pypi/esphome@1.18.0b1
- pkg:pypi/esphome@1.18.0b2
- pkg:pypi/esphome@1.18.0b3
- pkg:pypi/esphome@1.18.0b4
- pkg:pypi/esphome@1.19.0
- pkg:pypi/esphome@1.19.0b1
- pkg:pypi/esphome@1.19.0b2
- pkg:pypi/esphome@1.19.0b3
- pkg:pypi/esphome@1.19.0b4
- pkg:pypi/esphome@1.19.0b5
- pkg:pypi/esphome@1.19.0b6
- pkg:pypi/esphome@1.19.0b7
- pkg:pypi/esphome@1.19.1
- pkg:pypi/esphome@1.19.2
- pkg:pypi/esphome@1.19.3
- pkg:pypi/esphome@1.19.4
- pkg:pypi/esphome@1.20.0
- pkg:pypi/esphome@1.20.0b1
- pkg:pypi/esphome@1.20.0b2
- pkg:pypi/esphome@1.20.0b3
- pkg:pypi/esphome@1.20.0b4
- pkg:pypi/esphome@1.20.0b5
- pkg:pypi/esphome@1.20.0b6
- pkg:pypi/esphome@1.20.1
- pkg:pypi/esphome@1.20.2
- pkg:pypi/esphome@1.20.3
- pkg:pypi/esphome@1.20.4
- pkg:pypi/esphome@1.21.0b1
- pkg:pypi/esphome@1.21.0b2
- pkg:pypi/esphome@1.21.0b3
- pkg:pypi/esphome@2021.8.0
- pkg:pypi/esphome@2021.8.1
- pkg:pypi/esphome@2021.8.2
- pkg:pypi/esphome@2021.9.0
- pkg:pypi/esphome@2021.9.0b1
- pkg:pypi/esphome@2021.9.0b2
- pkg:pypi/esphome@2021.9.0b3
- pkg:pypi/esphome@2021.9.0b4
- pkg:pypi/esphome@2021.9.0b5
- pkg:pypi/esphome@2021.9.1
aliases:
- CVE-2021-41104
- GHSA-48mj-p7x2-5jfm
fixed_purl:
- pkg:pypi/esphome@2021.9.2
references:
- id: 163412
  reference_id: ''
  url: https://github.com/esphome/esphome/commit/be965a60eba6bb769e2a5afdbc8eed132f077a59
- id: 163414
  reference_id: ''
  url: https://github.com/esphome/esphome/pull/2409/commits/207cde1667d8c799a197b78ca8a5a14de8d5ca1e
- id: 163415
  reference_id: ''
  url: https://github.com/esphome/esphome/releases/tag/2021.9.2
- id: 163413
  reference_id: CVE-2021-41104
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-41104
- id: 163416
  reference_id: GHSA-48mj-p7x2-5jfm
  url: https://github.com/advisories/GHSA-48mj-p7x2-5jfm
- id: 163411
  reference_id: GHSA-48mj-p7x2-5jfm
  url: https://github.com/esphome/esphome/security/advisories/GHSA-48mj-p7x2-5jfm
severities:
- id: 24367
  reference_id: 163416
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
- id: 24366
  reference_id: 163411
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: Basic auth bypass in esphome
vulnerability_id: VCID-7um7-1zms-aaak
weaknesses: []
