pacakge: pkg:deb/debian/libcgi-application-perl
versions:
  - purl: pkg:deb/debian/libcgi-application-perl@4.50-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.50-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.50-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.50-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.50-4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.50-4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61%2B~1.21%2B~1.00%2B~1.01-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61%2B~1.21%2B~1.00%2B~1.01-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61%2B~1.21%2B~1.00%2B~1.01-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
  - purl: pkg:deb/debian/libcgi-application-perl@4.61%2B~1.21%2B~1.00%2B~1.01-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
