package: pkg:deb/debian/fontconfig
versions:
  - purl: pkg:deb/debian/fontconfig@2.11.0-6.5?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.11.0-6.5?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.11.0-6.5?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.11.0-6.5?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.11.0-6.7?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.11.0-6.7?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.5?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.13.1-4.5?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.14.1-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/debian/fontconfig@2.14.1-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
