affected_purls: []
aliases:
- CVE-2021-29622
fixed_purl:
- pkg:deb/debian/prometheus@0?distro=sid
- pkg:deb/debian/prometheus@2.24.1%2Bds-1?distro=sid
- pkg:deb/debian/prometheus@2.42.0%2Bds-5?distro=sid
- pkg:deb/debian/prometheus@2.7.1%2Bds-3?distro=sid
references: []
severities: []
summary: Prometheus is an open-source monitoring system and time series database.
  In 2.23.0, Prometheus changed its default UI to the New ui. To ensure a seamless
  transition, the URL's prefixed by /new redirect to /. Due to a bug in the code,
  it is possible for an attacker to craft an URL that can redirect to any other URL,
  in the /new endpoint. If a user visits a prometheus server with a specially crafted
  address, they can be redirected to an arbitrary URL. The issue was patched in the
  2.26.1 and 2.27.1 releases. In 2.28.0, the /new endpoint will be removed completely.
  The workaround is to disable access to /new via a reverse proxy in front of Prometheus.
vulnerability_id: VCID-n8gf-we7w-aaan
weaknesses: []
