affected_purls:
- pkg:pypi/ansible@1.0
- pkg:pypi/ansible@1.1
- pkg:pypi/ansible@1.2
- pkg:pypi/ansible@1.2.1
aliases:
- CVE-2021-3447
fixed_purl:
- pkg:pypi/ansible@1.2.2
references:
- id: 183545
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1939349
- id: 183544
  reference_id: CVE-2021-3447
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-3447
severities: []
summary: 'Inclusion of Sensitive Information in Log Files

  A flaw was found in several ansible modules, where parameters containing credentials,
  such as secrets, were being logged in plain-text on managed nodes, as well as being
  made visible on the controller node when run in verbose mode. These parameters were
  not protected by the `no_log` feature. An attacker can take advantage of this information
  to steal those credentials, provided when they have access to the log files containing
  them. The highest threat from this vulnerability is to data confidentiality. This
  flaw affects Red Hat Ansible Automation Platform and Ansible Tower'
vulnerability_id: VCID-7hwz-xfjc-aaac
weaknesses: []
