affected_purls:
- pkg:pypi/ansible@2.10.0
- pkg:pypi/ansible@2.10.0a1
- pkg:pypi/ansible@2.10.0a2
- pkg:pypi/ansible@2.10.0a3
- pkg:pypi/ansible@2.10.0a4
- pkg:pypi/ansible@2.10.0a5
- pkg:pypi/ansible@2.10.0a6
- pkg:pypi/ansible@2.10.0a7
- pkg:pypi/ansible@2.10.0a8
- pkg:pypi/ansible@2.10.0a9
- pkg:pypi/ansible@2.10.0b1
- pkg:pypi/ansible@2.10.0b2
- pkg:pypi/ansible@2.10.0rc1
- pkg:pypi/ansible@2.10.1
- pkg:pypi/ansible@2.10.2
- pkg:pypi/ansible@2.10.3
- pkg:pypi/ansible@2.10.4
- pkg:pypi/ansible@2.10.5
- pkg:pypi/ansible@2.10.6
- pkg:pypi/ansible@2.10.7
- pkg:pypi/ansible@2.5.0
- pkg:pypi/ansible@2.5.1
- pkg:pypi/ansible@2.5.10
- pkg:pypi/ansible@2.5.11
- pkg:pypi/ansible@2.5.12
- pkg:pypi/ansible@2.5.13
- pkg:pypi/ansible@2.5.14
- pkg:pypi/ansible@2.5.15
- pkg:pypi/ansible@2.5.2
- pkg:pypi/ansible@2.5.3
- pkg:pypi/ansible@2.5.4
- pkg:pypi/ansible@2.5.5
- pkg:pypi/ansible@2.5.6
- pkg:pypi/ansible@2.5.7
- pkg:pypi/ansible@2.5.8
- pkg:pypi/ansible@2.5.9
- pkg:pypi/ansible@2.6.0
- pkg:pypi/ansible@2.6.0a1
- pkg:pypi/ansible@2.6.0a2
- pkg:pypi/ansible@2.6.0rc1
- pkg:pypi/ansible@2.6.0rc2
- pkg:pypi/ansible@2.6.0rc3
- pkg:pypi/ansible@2.6.0rc4
- pkg:pypi/ansible@2.6.0rc5
- pkg:pypi/ansible@2.6.1
- pkg:pypi/ansible@2.6.10
- pkg:pypi/ansible@2.6.11
- pkg:pypi/ansible@2.6.12
- pkg:pypi/ansible@2.6.13
- pkg:pypi/ansible@2.6.14
- pkg:pypi/ansible@2.6.15
- pkg:pypi/ansible@2.6.16
- pkg:pypi/ansible@2.6.17
- pkg:pypi/ansible@2.6.18
- pkg:pypi/ansible@2.6.19
- pkg:pypi/ansible@2.6.2
- pkg:pypi/ansible@2.6.20
- pkg:pypi/ansible@2.6.3
- pkg:pypi/ansible@2.6.4
- pkg:pypi/ansible@2.6.5
- pkg:pypi/ansible@2.6.6
- pkg:pypi/ansible@2.6.7
- pkg:pypi/ansible@2.6.8
- pkg:pypi/ansible@2.6.9
- pkg:pypi/ansible@2.7.0
- pkg:pypi/ansible@2.7.0a1
- pkg:pypi/ansible@2.7.0b1
- pkg:pypi/ansible@2.7.0.dev0
- pkg:pypi/ansible@2.7.0rc1
- pkg:pypi/ansible@2.7.0rc2
- pkg:pypi/ansible@2.7.0rc3
- pkg:pypi/ansible@2.7.0rc4
- pkg:pypi/ansible@2.7.1
- pkg:pypi/ansible@2.7.10
- pkg:pypi/ansible@2.7.11
- pkg:pypi/ansible@2.7.12
- pkg:pypi/ansible@2.7.13
- pkg:pypi/ansible@2.7.14
- pkg:pypi/ansible@2.7.15
- pkg:pypi/ansible@2.7.16
- pkg:pypi/ansible@2.7.17
- pkg:pypi/ansible@2.7.18
- pkg:pypi/ansible@2.7.2
- pkg:pypi/ansible@2.7.3
- pkg:pypi/ansible@2.7.4
- pkg:pypi/ansible@2.7.5
- pkg:pypi/ansible@2.7.6
- pkg:pypi/ansible@2.7.7
- pkg:pypi/ansible@2.7.8
- pkg:pypi/ansible@2.7.9
- pkg:pypi/ansible@2.8.0
- pkg:pypi/ansible@2.8.0a1
- pkg:pypi/ansible@2.8.0b1
- pkg:pypi/ansible@2.8.0rc1
- pkg:pypi/ansible@2.8.0rc2
- pkg:pypi/ansible@2.8.0rc3
- pkg:pypi/ansible@2.8.1
- pkg:pypi/ansible@2.8.10
- pkg:pypi/ansible@2.8.11
- pkg:pypi/ansible@2.8.12
- pkg:pypi/ansible@2.8.13
- pkg:pypi/ansible@2.8.14
- pkg:pypi/ansible@2.8.15
- pkg:pypi/ansible@2.8.16
- pkg:pypi/ansible@2.8.16rc1
- pkg:pypi/ansible@2.8.17
- pkg:pypi/ansible@2.8.17rc1
- pkg:pypi/ansible@2.8.18
- pkg:pypi/ansible@2.8.18rc1
- pkg:pypi/ansible@2.8.19
- pkg:pypi/ansible@2.8.19rc1
- pkg:pypi/ansible@2.8.2
- pkg:pypi/ansible@2.8.20
- pkg:pypi/ansible@2.8.20rc1
- pkg:pypi/ansible@2.8.3
- pkg:pypi/ansible@2.8.4
- pkg:pypi/ansible@2.8.5
- pkg:pypi/ansible@2.8.6
- pkg:pypi/ansible@2.8.7
- pkg:pypi/ansible@2.8.8
- pkg:pypi/ansible@2.8.9
- pkg:pypi/ansible@2.9.0
- pkg:pypi/ansible@2.9.0b1
- pkg:pypi/ansible@2.9.0rc1
- pkg:pypi/ansible@2.9.0rc2
- pkg:pypi/ansible@2.9.0rc3
- pkg:pypi/ansible@2.9.0rc4
- pkg:pypi/ansible@2.9.0rc5
- pkg:pypi/ansible@2.9.1
- pkg:pypi/ansible@2.9.10
- pkg:pypi/ansible@2.9.11
- pkg:pypi/ansible@2.9.12
- pkg:pypi/ansible@2.9.13
- pkg:pypi/ansible@2.9.14
- pkg:pypi/ansible@2.9.14rc1
- pkg:pypi/ansible@2.9.15
- pkg:pypi/ansible@2.9.15rc1
- pkg:pypi/ansible@2.9.16
- pkg:pypi/ansible@2.9.16rc1
- pkg:pypi/ansible@2.9.17
- pkg:pypi/ansible@2.9.17rc1
- pkg:pypi/ansible@2.9.18
- pkg:pypi/ansible@2.9.18rc1
- pkg:pypi/ansible@2.9.19
- pkg:pypi/ansible@2.9.19rc1
- pkg:pypi/ansible@2.9.2
- pkg:pypi/ansible@2.9.20
- pkg:pypi/ansible@2.9.20rc1
- pkg:pypi/ansible@2.9.21
- pkg:pypi/ansible@2.9.21rc1
- pkg:pypi/ansible@2.9.22
- pkg:pypi/ansible@2.9.22rc1
- pkg:pypi/ansible@2.9.23
- pkg:pypi/ansible@2.9.23rc1
- pkg:pypi/ansible@2.9.24
- pkg:pypi/ansible@2.9.24rc1
- pkg:pypi/ansible@2.9.25
- pkg:pypi/ansible@2.9.25rc1
- pkg:pypi/ansible@2.9.26
- pkg:pypi/ansible@2.9.26rc1
- pkg:pypi/ansible@2.9.27
- pkg:pypi/ansible@2.9.27rc1
- pkg:pypi/ansible@2.9.3
- pkg:pypi/ansible@2.9.4
- pkg:pypi/ansible@2.9.5
- pkg:pypi/ansible@2.9.6
- pkg:pypi/ansible@2.9.7
- pkg:pypi/ansible@2.9.8
- pkg:pypi/ansible@2.9.9
- pkg:pypi/ansible@3.0.0
- pkg:pypi/ansible@3.0.0b1
- pkg:pypi/ansible@3.0.0rc1
- pkg:pypi/ansible@3.1.0
- pkg:pypi/ansible@3.2.0
- pkg:pypi/ansible@3.3.0
- pkg:pypi/ansible@3.4.0
- pkg:pypi/ansible@4.0.0
- pkg:pypi/ansible@4.0.0a1
- pkg:pypi/ansible@4.0.0a2
- pkg:pypi/ansible@4.0.0a3
- pkg:pypi/ansible@4.0.0a4
- pkg:pypi/ansible@4.0.0b1
- pkg:pypi/ansible@4.0.0b2
- pkg:pypi/ansible@4.0.0rc1
- pkg:pypi/ansible@4.1.0
- pkg:pypi/ansible@4.10.0
- pkg:pypi/ansible@4.2.0
- pkg:pypi/ansible@4.3.0
- pkg:pypi/ansible@4.4.0
- pkg:pypi/ansible@4.5.0
- pkg:pypi/ansible@4.6.0
- pkg:pypi/ansible@4.7.0
- pkg:pypi/ansible@4.8.0
- pkg:pypi/ansible@4.9.0
- pkg:pypi/ansible@5.0.0a1
- pkg:pypi/ansible@5.0.0a2
- pkg:pypi/ansible@5.0.0a3
- pkg:pypi/ansible@5.0.0b1
- pkg:pypi/ansible@5.0.0b2
- pkg:pypi/ansible@5.0.0rc1
- pkg:pypi/ansible@5.0.1
- pkg:pypi/ansible@5.1.0
- pkg:pypi/ansible@5.10.0
- pkg:pypi/ansible@5.2.0
- pkg:pypi/ansible@5.3.0
- pkg:pypi/ansible@5.4.0
- pkg:pypi/ansible@5.5.0
- pkg:pypi/ansible@5.6.0
- pkg:pypi/ansible@5.7.0
- pkg:pypi/ansible@5.7.1
- pkg:pypi/ansible@5.8.0
- pkg:pypi/ansible@5.9.0
- pkg:pypi/ansible@6.0.0
- pkg:pypi/ansible@6.0.0a1
- pkg:pypi/ansible@6.0.0a2
- pkg:pypi/ansible@6.0.0a3
- pkg:pypi/ansible@6.0.0b1
- pkg:pypi/ansible@6.0.0b2
- pkg:pypi/ansible@6.0.0rc1
- pkg:pypi/ansible@6.1.0
- pkg:pypi/ansible@6.2.0
- pkg:pypi/ansible@6.3.0
- pkg:pypi/ansible@6.4.0
- pkg:pypi/ansible@6.5.0
- pkg:pypi/ansible@7.0.0a1
- pkg:pypi/ansible@7.0.0a2
aliases:
- CVE-2022-3697
- GHSA-cpx3-93w7-457x
fixed_purl: []
references:
- id: 171660
  reference_id: ''
  url: https://github.com/ansible/ansible/pull/35749
- id: 171659
  reference_id: ''
  url: https://github.com/ansible-collections/amazon.aws/pull/1199
- id: 171661
  reference_id: ''
  url: https://github.com/ansible-community/ansible-build-data/blob/main/6/CHANGELOG-v6.rst
- id: 171658
  reference_id: CVE-2022-3697
  url: https://nvd.nist.gov/vuln/detail/CVE-2022-3697
- id: 171662
  reference_id: GHSA-cpx3-93w7-457x
  url: https://github.com/advisories/GHSA-cpx3-93w7-457x
severities:
- id: 26666
  reference_id: 171662
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: amazon.aws.ec2_instance leaks passwords into logs when tower_callback.windows
  is set
vulnerability_id: VCID-fgu1-69zn-aaab
weaknesses: []
