affected_purls:
- pkg:pypi/ansible@1.0
- pkg:pypi/ansible-vault@1.0.0
- pkg:pypi/ansible-vault@1.0.1
- pkg:pypi/ansible-vault@1.0.2
- pkg:pypi/ansible-vault@1.0.3
- pkg:pypi/ansible-vault@1.0.4
aliases:
- CVE-2017-2809
- GHSA-c2w9-48qc-qpj4
fixed_purl:
- pkg:pypi/ansible@1.1
- pkg:pypi/ansible-vault@1.0.5
references:
- id: 142407
  reference_id: ''
  url: https://github.com/tomoh1r/ansible-vault/blob/v1.0.5/CHANGES.txt
- id: 142405
  reference_id: ''
  url: https://github.com/tomoh1r/ansible-vault/commit/3f8f659ef443ab870bb19f95d43543470168ae04
- id: 142404
  reference_id: ''
  url: https://github.com/tomoh1r/ansible-vault/issues/4
- id: 142408
  reference_id: ''
  url: https://www.talosintelligence.com/vulnerability_reports/TALOS-2017-0305
- id: 142409
  reference_id: ''
  url: http://www.securityfocus.com/bid/100824
- id: 142403
  reference_id: CVE-2017-2809
  url: https://nvd.nist.gov/vuln/detail/CVE-2017-2809
- id: 142406
  reference_id: GHSA-c2w9-48qc-qpj4
  url: https://github.com/advisories/GHSA-c2w9-48qc-qpj4
severities:
- id: 19833
  reference_id: 142406
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: Code injection in ansible
vulnerability_id: VCID-xh4h-rrzx-aaag
weaknesses: []
