package: pkg:deb/debian/golang-github-prometheus-exporter-toolkit
versions:
  - purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.5.1-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-u37h-3621-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.8.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-u37h-3621-aaaj
