package: pkg:deb/ubuntu/debian-lan-config
versions:
  - purl: pkg:deb/ubuntu/debian-lan-config@0.10
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.11
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.12
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.13
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.14
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.15
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.17
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.18
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.19
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.20
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.21
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.22
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.23
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.23%2Bdeb9u1build0.18.04.1
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.25
    affected_by_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/debian-lan-config@0.26
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
