vulnerability_id: VCID-r6zg-c9a5-aaah
aliases:
  - CVE-2019-3826
summary: A stored, DOM based, cross-site scripting (XSS) flaw was found in Prometheus before
  version 2.7.1. An attacker could exploit this by convincing an authenticated user to visit
  a crafted URL on a Prometheus server, allowing for the execution and persistent storage of
  arbitrary scripts.
severities:
  - id: 693754
    reference_id: 1454353
    scoring_system: generic_textual
    value: Low
    scoring_elements:
  - id: 613055
    reference_id: 933590
    scoring_system: cvssv3
    value: '6.1'
    scoring_elements: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
  - id: 693755
    reference_id: 1454354
    scoring_system: generic_textual
    value: Low
    scoring_elements:
  - id: 693756
    reference_id: 796097
    scoring_system: generic_textual
    value: Low
    scoring_elements:
  - id: 406198
    reference_id: 796098
    scoring_system: cvssv2
    value: '4.3'
    scoring_elements: AV:N/AC:M/Au:N/C:N/I:P/A:N
  - id: 406196
    reference_id: 796098
    scoring_system: cvssv3
    value: '6.1'
    scoring_elements: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
references:
  - id: 1454353
    url: http://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-3826.html
    reference_id:
  - id: 689882
    url: https://access.redhat.com/errata/RHBA-2019:0327
    reference_id:
  - id: 933590
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2019-3826.json
    reference_id:
  - id: 796094
    url: https://advisory.checkmarx.net/advisory/CX-2019-4297
    reference_id:
  - id: 796095
    url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3826
    reference_id:
  - id: 1454354
    url: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3826
    reference_id:
  - id: 796096
    url: https://github.com/prometheus/prometheus/commit/62e591f9
    reference_id:
  - id: 796097
    url: https://github.com/prometheus/prometheus/pull/5163
    reference_id:
  - id: 2644
    url: https://lists.apache.org/thread.html/r48d5019bd42e0770f7e5351e420a63a41ff1f16924942442c6aff6a8@%3Ccommits.zookeeper.apache.org%3E
    reference_id:
  - id: 2651
    url: https://lists.apache.org/thread.html/r8e3f7da12bf5750b0a02e69a78a61073a2ac950eed7451ce70a65177@%3Ccommits.zookeeper.apache.org%3E
    reference_id:
  - id: 2659
    url: https://lists.apache.org/thread.html/rdf2a0d94c3b5b523aeff7741ae71347415276062811b687f30ea6573@%3Ccommits.zookeeper.apache.org%3E
    reference_id:
  - id: 104582
    url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921615
    reference_id: 921615
  - id: 796099
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:prometheus:prometheus:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:prometheus:prometheus:*:*:*:*:*:*:*:*
  - id: 625785
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:redhat:openshift_container_platform:3.11:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:redhat:openshift_container_platform:3.11:*:*:*:*:*:*:*
  - id: 796098
    url: https://nvd.nist.gov/vuln/detail/CVE-2019-3826
    reference_id: CVE-2019-3826
  - id: 933589
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1672865
    reference_id: RHBA-2019:0326
weaknesses: []
