package: pkg:deb/debian/flask-security
versions:
  - purl: pkg:deb/debian/flask-security@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@1.7.5-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@1.7.5-2
    affected_by_vulnerabilities:
      - VCID-58bq-b5be-aaap
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/flask-security@1.7.5-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-58bq-b5be-aaap
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@4.0.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@4.0.0-1
    affected_by_vulnerabilities:
      - VCID-58bq-b5be-aaap
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/flask-security@4.0.0-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-58bq-b5be-aaap
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@4.0.0-1%2Bdeb11u1
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-58bq-b5be-aaap
  - purl: pkg:deb/debian/flask-security@5.0.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-58bq-b5be-aaap
  - purl: pkg:deb/debian/flask-security@5.0.2-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@5.1.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@5.1.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
  - purl: pkg:deb/debian/flask-security@5.1.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qzdt-zup1-aaam
