pacakge: pkg:deb/debian/editorconfig-core
versions:
  - purl: pkg:deb/debian/editorconfig-core@0.12.1-1.1?distro=sid
    affected_by_vulnerabilities:
      - VCID-89zs-ezhr-aaag
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/editorconfig-core@0.12.5-2.2?distro=sid
    affected_by_vulnerabilities:
      - VCID-89zs-ezhr-aaag
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/editorconfig-core@0.12.6-0.1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-89zs-ezhr-aaag
