pacakge: pkg:deb/debian/debian-lan-config
versions:
  - purl: pkg:deb/debian/debian-lan-config@0.23%2Bdeb9u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.23%2Bdeb9u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.25%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.25%2Bdeb10u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.25%2Bdeb10u1?distro=buster
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.25%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.25%2Bdeb10u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.26?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.26?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.26?distro=buster
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.26?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.26?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.28?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.28?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.28?distro=buster
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.28?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-lan-config@0.28?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
