pacakge: pkg:deb/debian/calamares-settings-debian
versions:
  - purl: pkg:deb/debian/calamares-settings-debian@10.0.20-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@10.0.20-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@10.0.20-1%2Bdeb10u4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@10.0.20-1%2Bdeb10u4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@10.0.23-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@10.0.23-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@11.0.5-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@11.0.5-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@12.0.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@12.0.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@12.0.3-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@12.0.3-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@12.0.4-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
  - purl: pkg:deb/debian/calamares-settings-debian@12.0.5-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-te29-tva5-aaar
