affected_purls: []
aliases:
- CVE-2021-39939
fixed_purl:
- pkg:deb/debian/gitlab-ci-multi-runner@0?distro=sid
- pkg:deb/debian/gitlab-ci-multi-runner@14.10.1-1?distro=sid
references: []
severities: []
summary: An uncontrolled resource consumption vulnerability in GitLab Runner affecting
  all versions starting from 13.7 before 14.3.6, all versions starting from 14.4 before
  14.4.4, all versions starting from 14.5 before 14.5.2, allows an attacker triggering
  a job with a specially crafted docker image to exhaust resources on runner manager
vulnerability_id: VCID-d4xc-sn6h-aaaa
weaknesses: []
