pacakge: pkg:deb/ubuntu/composer
versions:
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha10%2B20150511-1
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha10%2B20150602-1
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha10%2B20150602-2
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha11-1
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha11-1ubuntu1
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha11-2
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha11-3
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~alpha9%2Bdfsg-1
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~beta1-1
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~beta1-1ubuntu1
    affected_by_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/composer@1.0.0~beta2-1
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-6n2k-dthb-aaaa
