pacakge: pkg:deb/debian/commons-configuration2
versions:
  - purl: pkg:deb/debian/commons-configuration2@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-fsb5-nqdc-aaap
  - purl: pkg:deb/debian/commons-configuration2@2.2-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities:
      - VCID-fsb5-nqdc-aaap
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
  - purl: pkg:deb/debian/commons-configuration2@2.2-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities:
      - VCID-fsb5-nqdc-aaap
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
  - purl: pkg:deb/debian/commons-configuration2@2.7-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
  - purl: pkg:deb/debian/commons-configuration2@2.7-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
  - purl: pkg:deb/debian/commons-configuration2@2.7-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-fsb5-nqdc-aaap
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
  - purl: pkg:deb/debian/commons-configuration2@2.7-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-fsb5-nqdc-aaap
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
  - purl: pkg:deb/debian/commons-configuration2@2.8.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
      - VCID-fsb5-nqdc-aaap
  - purl: pkg:deb/debian/commons-configuration2@2.8.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
      - VCID-fsb5-nqdc-aaap
  - purl: pkg:deb/debian/commons-configuration2@2.8.0-1~deb11u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
      - VCID-fsb5-nqdc-aaap
  - purl: pkg:deb/debian/commons-configuration2@2.8.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-c9y6-hnbf-aaaa
      - VCID-fsb5-nqdc-aaap
