pacakge: pkg:alpine/composer
versions:
  - purl: pkg:alpine/composer@2.0.13-r0?arch=aarch64&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=aarch64&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=aarch64&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=aarch64&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=aarch64&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armhf&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armhf&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armhf&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armhf&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armhf&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armv7&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armv7&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armv7&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armv7&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=armv7&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=mips64&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=ppc64le&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=ppc64le&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=ppc64le&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=ppc64le&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=ppc64le&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=s390x&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=s390x&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=s390x&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=s390x&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=s390x&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86_64&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86_64&distroversion=v3.13&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86_64&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86_64&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.0.13-r0?arch=x86_64&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-2adq-7cbg-aaap
  - purl: pkg:alpine/composer@2.1.9-r0?arch=aarch64&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=aarch64&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=aarch64&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=aarch64&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armhf&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armhf&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armhf&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armhf&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armv7&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armv7&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armv7&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=armv7&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=ppc64le&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=ppc64le&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=ppc64le&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=ppc64le&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=s390x&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=s390x&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=s390x&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=s390x&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86_64&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86_64&distroversion=v3.14&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86_64&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.1.9-r0?arch=x86_64&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-kg1u-ehxt-aaab
  - purl: pkg:alpine/composer@2.2.12-r0?arch=aarch64&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.2.12-r0?arch=armhf&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.2.12-r0?arch=armv7&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.2.12-r0?arch=ppc64le&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.2.12-r0?arch=s390x&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.2.12-r0?arch=x86&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.2.12-r0?arch=x86_64&distroversion=v3.15&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=aarch64&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=aarch64&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=armhf&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=armhf&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=armv7&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=armv7&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=ppc64le&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=ppc64le&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=s390x&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=s390x&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=x86&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=x86&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=x86_64&distroversion=edge&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
  - purl: pkg:alpine/composer@2.3.5-r0?arch=x86_64&distroversion=v3.16&reponame=community
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tpwa-ceu9-aaas
