package: pkg:deb/ubuntu/libconfig-model-perl
versions:
  - purl: pkg:deb/ubuntu/libconfig-model-perl@0.635-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@0.636-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@0.640-2
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@0.640-3
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@0.640-4
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@0.642-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.202-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.204-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.205-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.209-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.215-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.216-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.217-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.220-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.221-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.222-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.223-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.226-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.242-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.243-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.244-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.246-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.247-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.250-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.257-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.259-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.260-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@1.265-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.005-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.013-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.015-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.018-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.019-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.020-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.021-2
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.021-3
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.026-3
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.027-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.028-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.029-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.029-2
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.035-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.036-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.037-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.038-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.040-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.045-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.045-2
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.046-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.046-2
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.047-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.054-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.055-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.056-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.057-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.058-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.059-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.061-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.070-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.071-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.071-2
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.071-3
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.073-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.074-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.075-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.075-2
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.077-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.078-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.082-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.083-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.085-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.086-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.087-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.088-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.092-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.094-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.096-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.097-1
    affected_by_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libconfig-model-perl@2.097-2
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
