pacakge: pkg:deb/debian/cloud-init
versions:
  - purl: pkg:deb/debian/cloud-init@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@0.7.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
  - purl: pkg:deb/debian/cloud-init@0.7.1-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
  - purl: pkg:deb/debian/cloud-init@0.7.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
  - purl: pkg:deb/debian/cloud-init@0.7.1-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
  - purl: pkg:deb/debian/cloud-init@0.7.9-2?distro=stretch
    affected_by_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-rgk6-gc76-aaar
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@0.7.9-2
    affected_by_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-rgk6-gc76-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/cloud-init@0.7.9-2?distro=stretch
    affected_by_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-rgk6-gc76-aaar
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@0.7.9-2%2Bdeb9u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@0.7.9-2%2Bdeb9u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@18.3-6?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@18.3-6?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@18.3-6?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@18.3-6?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@19.4-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
  - purl: pkg:deb/debian/cloud-init@19.4-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
  - purl: pkg:deb/debian/cloud-init@19.4-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
  - purl: pkg:deb/debian/cloud-init@19.4-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
  - purl: pkg:deb/debian/cloud-init@20.2-2~bpo10%2B1
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@20.4.1-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@20.4.1-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@20.4.1-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@20.4.1-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@22.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-nphr-p5x9-aaaj
  - purl: pkg:deb/debian/cloud-init@22.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
  - purl: pkg:deb/debian/cloud-init@22.2-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@22.2-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@22.2-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@22.2-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@22.2-3.1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@22.2-3.1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
  - purl: pkg:deb/debian/cloud-init@22.4.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5n5e-af5d-aaae
      - VCID-5sez-wgc8-aaaq
      - VCID-bjwp-wq7y-aaad
      - VCID-nphr-p5x9-aaaj
      - VCID-rgk6-gc76-aaar
      - VCID-zbat-x8sj-aaae
