package: pkg:deb/debian/kconfig
versions:
  - purl: pkg:deb/debian/kconfig@5.100.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.100.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.101.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.102.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.103.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.103.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.28.0-2%2Bdeb9u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.28.0-2%2Bdeb9u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-1%2Bdeb10u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-1%2Bdeb10u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-1%2Bdeb10u1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.54.0-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.78.0-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.78.0-4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.78.0-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.78.0-4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.94.0-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.94.0-3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.94.0-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.94.0-3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.94.0-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.94.0-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.96.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.96.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.97.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.97.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.97.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.97.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.98.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.98.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.98.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.98.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.98.0-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/debian/kconfig@5.98.0-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
