package: pkg:deb/debian/gnome-settings-daemon
versions:
  - purl: pkg:deb/debian/gnome-settings-daemon@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@0?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@0?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.22.2-2%2Bdeb9u2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.22.2-2%2Bdeb9u2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.30.2-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.30.2-3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.30.2-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.30.2-3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.38.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.38.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.38.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@3.38.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@42.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@42.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@42.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@42.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43.0-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43.0-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43.0-3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43.0-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43~beta-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43~beta-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43~rc-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
  - purl: pkg:deb/debian/gnome-settings-daemon@43~rc-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-jybc-489s-aaaq
