vulnerability_id: VCID-2qwr-a8ug-aaar
aliases:
  - CVE-2020-8565
summary: In Kubernetes, if the logging level is set to at least 9, authorization and bearer
  tokens will be written to log files. This can occur both in API server logs and client tool
  output like kubectl. This affects <= v1.19.3, <= v1.18.10, <= v1.17.13, < v1.20.0-alpha2.
severities:
  - id: 609283
    reference_id: 930824
    scoring_system: cvssv3
    value: '5.3'
    scoring_elements: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N
  - id: 491948
    reference_id: 854932
    scoring_system: cvssv2
    value: '2.1'
    scoring_elements: AV:L/AC:L/Au:N/C:P/I:N/A:N
  - id: 491946
    reference_id: 854932
    scoring_system: cvssv3
    value: '5.5'
    scoring_elements: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N
  - id: 53433
    reference_id: 178458
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 603759
    reference_id: 926763
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 602732
    reference_id: 926010
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 930824
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2020-8565.json
    reference_id:
  - id: 854931
    url: https://github.com/kubernetes/kubernetes/issues/95623
    reference_id:
  - id: 854890
    url: https://groups.google.com/g/kubernetes-security-discuss/c/vm-HcrFUOCs/m/36utxAM5CwAJ
    reference_id:
  - id: 42772
    url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972649
    reference_id: 972649
  - id: 669448
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  - id: 854932
    url: https://nvd.nist.gov/vuln/detail/CVE-2020-8565
    reference_id: CVE-2020-8565
  - id: 930823
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1886638
    reference_id: RHBA-2021:3003
  - id: 178458
    url: https://access.redhat.com/errata/RHSA-2021:2041
    reference_id: RHSA-2021:2041
  - id: 926763
    url: https://access.redhat.com/errata/RHSA-2021:5085
    reference_id: RHSA-2021:5085
  - id: 926010
    url: https://access.redhat.com/errata/RHSA-2021:5086
    reference_id: RHSA-2021:5086
weaknesses: []
