vulnerability_id: VCID-c4gh-vs6u-aaaj
aliases:
  - CVE-2020-8566
summary: In Kubernetes clusters using Ceph RBD as a storage provisioner, with logging level
  of at least 4, Ceph RBD admin secrets can be written to logs. This occurs in kube-controller-manager's
  logs during provisioning of Ceph RBD persistent claims. This affects < v1.19.3, < v1.18.10,
  < v1.17.13.
severities:
  - id: 609286
    reference_id: 930826
    scoring_system: cvssv3
    value: '5.3'
    scoring_elements: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N
  - id: 609285
    reference_id: 930825
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 491908
    reference_id: 854892
    scoring_system: cvssv2
    value: '2.1'
    scoring_elements: AV:L/AC:L/Au:N/C:P/I:N/A:N
  - id: 491906
    reference_id: 854892
    scoring_system: cvssv3
    value: '5.5'
    scoring_elements: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N
  - id: 66837
    reference_id: '195977'
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 608535
    reference_id: 930269
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 930826
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2020-8566.json
    reference_id:
  - id: 854889
    url: https://github.com/kubernetes/kubernetes/issues/95624
    reference_id:
  - id: 854890
    url: https://groups.google.com/g/kubernetes-security-discuss/c/vm-HcrFUOCs/m/36utxAM5CwAJ
    reference_id:
  - id: 854891
    url: https://security.netapp.com/advisory/ntap-20210122-0006/
    reference_id:
  - id: 930825
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1886640
    reference_id: 1886640
  - id: 42771
    url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972341
    reference_id: 972341
  - id: 669448
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  - id: 854892
    url: https://nvd.nist.gov/vuln/detail/CVE-2020-8566
    reference_id: CVE-2020-8566
  - id: '195977'
    url: https://access.redhat.com/errata/RHSA-2020:5634
    reference_id: RHSA-2020:5634
  - id: 930269
    url: https://access.redhat.com/errata/RHSA-2021:0037
    reference_id: RHSA-2021:0037
weaknesses: []
