vulnerability_id: VCID-ysh4-ardx-aaah
aliases:
  - CVE-2020-8552
summary: The Kubernetes API server component in versions prior to 1.15.9, 1.16.0-1.16.6, and
  1.17.0-1.17.2 has been found to be vulnerable to a denial of service attack via successful
  API requests.
severities:
  - id: 53180
    reference_id: 178197
    scoring_system: cvssv3
    value: '4.3'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L
  - id: 491900
    reference_id: 854885
    scoring_system: cvssv2
    value: '4.0'
    scoring_elements: AV:N/AC:L/Au:S/C:N/I:N/A:P
  - id: 491898
    reference_id: 854885
    scoring_system: cvssv3
    value: '4.3'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L
  - id: 53178
    reference_id: 178194
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 53177
    reference_id: 178193
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 53179
    reference_id: 178196
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 53176
    reference_id: 178190
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 178197
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2020-8552.json
    reference_id:
  - id: 854884
    url: https://github.com/kubernetes/kubernetes/issues/89378
    reference_id:
  - id: 854881
    url: https://groups.google.com/forum/#!topic/kubernetes-security-announce/2UOlsba2g0s
    reference_id:
  - id: 854882
    url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3SOCLOPTSYABTE4CLTSPDIFE6ZZZR4LX/
    reference_id:
  - id: 769825
    url: https://security.netapp.com/advisory/ntap-20200413-0003/
    reference_id:
  - id: 669448
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  - id: 854885
    url: https://nvd.nist.gov/vuln/detail/CVE-2020-8552
    reference_id: CVE-2020-8552
  - id: 178195
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1797909
    reference_id: RHBA-2020:0929
  - id: 178194
    url: https://access.redhat.com/errata/RHSA-2020:1526
    reference_id: RHSA-2020:1526
  - id: 178193
    url: https://access.redhat.com/errata/RHSA-2020:1527
    reference_id: RHSA-2020:1527
  - id: 178196
    url: https://access.redhat.com/errata/RHSA-2020:2306
    reference_id: RHSA-2020:2306
  - id: 178190
    url: https://access.redhat.com/errata/RHSA-2020:2992
    reference_id: RHSA-2020:2992
weaknesses: []
