vulnerability_id: VCID-j9nb-qsnr-aaad
aliases:
  - CVE-2017-1002102
summary: In Kubernetes versions 1.3.x, 1.4.x, 1.5.x, 1.6.x and prior to versions 1.7.14, 1.8.9
  and 1.9.4 containers using a secret, configMap, projected or downwardAPI volume can trigger
  deletion of arbitrary files/directories from the nodes where they are running.
severities:
  - id: 617980
    reference_id: 937171
    scoring_system: cvssv3
    value: '7.1'
    scoring_elements: CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H
  - id: 617979
    reference_id: 937170
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 250692
    reference_id: 669450
    scoring_system: cvssv2
    value: '6.3'
    scoring_elements: AV:L/AC:M/Au:N/C:N/I:C/A:C
  - id: 250690
    reference_id: 669450
    scoring_system: cvssv3
    value: '5.6'
    scoring_elements: CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:C/C:N/I:H/A:N
  - id: 617859
    reference_id: 937088
    scoring_system: rhas
    value: Important
    scoring_elements:
references:
  - id: 937171
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2017-1002102.json
    reference_id:
  - id: 669449
    url: https://github.com/kubernetes/kubernetes/issues/60814
    reference_id:
  - id: 937170
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1551818
    reference_id: 1551818
  - id: 42760
    url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894051
    reference_id: 894051
  - id: 669448
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  - id: 669450
    url: https://nvd.nist.gov/vuln/detail/CVE-2017-1002102
    reference_id: CVE-2017-1002102
  - id: 937088
    url: https://access.redhat.com/errata/RHSA-2018:0475
    reference_id: RHSA-2018:0475
weaknesses: []
