vulnerability_id: VCID-fr94-mwxc-aaac
aliases:
  - CVE-2015-7528
summary: Kubernetes before 1.2.0-alpha.5 allows remote attackers to read arbitrary pod logs
  via a container name.
severities:
  - id: 52500
    reference_id: 177351
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 203535
    reference_id: 614310
    scoring_system: cvssv2
    value: '5.0'
    scoring_elements: AV:N/AC:L/Au:N/C:P/I:N/A:N
  - id: 203533
    reference_id: 614310
    scoring_system: cvssv3
    value: '5.3'
    scoring_elements: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
  - id: 52502
    reference_id: 177353
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 614305
    url: http://rhn.redhat.com/errata/RHSA-2015-2615.html
    reference_id:
  - id: 614306
    url: https://access.redhat.com/errata/RHSA-2015:2544
    reference_id:
  - id: 177354
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2015-7528.json
    reference_id:
  - id: 614307
    url: https://github.com/kubernetes/kubernetes/pull/17886
    reference_id:
  - id: 614308
    url: https://github.com/kubernetes/kubernetes/releases/tag/v1.2.0-alpha.5
    reference_id:
  - id: 614309
    url: https://github.com/openshift/origin/pull/6113
    reference_id:
  - id: 177351
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1286745
    reference_id: 1286745
  - id: 614311
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:*:alpha.4:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:*:alpha.4:*:*:*:*:*:*
  - id: 159078
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:redhat:openshift:3.0:*:*:*:enterprise:*:*:*
    reference_id: cpe:2.3:a:redhat:openshift:3.0:*:*:*:enterprise:*:*:*
  - id: 614312
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:redhat:openshift:3.1:*:*:*:enterprise:*:*:*
    reference_id: cpe:2.3:a:redhat:openshift:3.1:*:*:*:enterprise:*:*:*
  - id: 614310
    url: https://nvd.nist.gov/vuln/detail/CVE-2015-7528
    reference_id: CVE-2015-7528
  - id: 177353
    url: https://access.redhat.com/errata/RHSA-2015:2615
    reference_id: RHSA-2015:2615
weaknesses: []
