vulnerability_id: VCID-eyq9-w8rq-aaap
aliases:
  - CVE-2020-8561
summary: A security issue was discovered in Kubernetes where actors that control the responses
  of MutatingWebhookConfiguration or ValidatingWebhookConfiguration requests are able to redirect
  kube-apiserver requests to private networks of the apiserver. If that user can view kube-apiserver
  logs when the log level is set to 10, they can view the redirected responses and headers in
  the logs.
severities:
  - id: 602541
    reference_id: 925868
    scoring_system: cvssv3
    value: '4.1'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:L/I:N/A:N
  - id: 602540
    reference_id: 925867
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 491932
    reference_id: 854918
    scoring_system: cvssv2
    value: '4.0'
    scoring_elements: AV:N/AC:L/Au:S/C:P/I:N/A:N
  - id: 491930
    reference_id: 854918
    scoring_system: cvssv3
    value: '4.1'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:L/I:N/A:N
references:
  - id: 925868
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2020-8561.json
    reference_id:
  - id: 854915
    url: https://github.com/kubernetes/kubernetes/issues/104720
    reference_id:
  - id: 854916
    url: https://groups.google.com/g/kubernetes-security-announce/c/RV2IhwcrQsY
    reference_id:
  - id: 854917
    url: https://security.netapp.com/advisory/ntap-20211014-0002/
    reference_id:
  - id: 925867
    url: https://bugzilla.redhat.com/show_bug.cgi?id=2000366
    reference_id: 2000366
  - id: 854919
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:1.20.11:-:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:1.20.11:-:*:*:*:*:*:*
  - id: 854920
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:1.21.5:-:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:1.21.5:-:*:*:*:*:*:*
  - id: 854921
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:1.22.2:-:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:1.22.2:-:*:*:*:*:*:*
  - id: 854918
    url: https://nvd.nist.gov/vuln/detail/CVE-2020-8561
    reference_id: CVE-2020-8561
weaknesses: []
