vulnerability_id: VCID-3guf-r76t-aaar
aliases:
  - CVE-2015-5305
summary: Directory traversal vulnerability in Kubernetes, as used in Red Hat OpenShift Enterprise
  3.0, allows attackers to write to arbitrary files via a crafted object type name, which is
  not properly handled before passing it to etcd.
severities:
  - id: 52818
    reference_id: 177750
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 38093
    reference_id: 159077
    scoring_system: cvssv2
    value: '6.4'
    scoring_elements: AV:N/AC:L/Au:N/C:N/I:P/A:P
  - id: 52819
    reference_id: 177751
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 177752
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2015-5305.json
    reference_id:
  - id: 177750
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1273969
    reference_id: 1273969
  - id: 159078
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:redhat:openshift:3.0:*:*:*:enterprise:*:*:*
    reference_id: cpe:2.3:a:redhat:openshift:3.0:*:*:*:enterprise:*:*:*
  - id: 159077
    url: https://nvd.nist.gov/vuln/detail/CVE-2015-5305
    reference_id: CVE-2015-5305
  - id: 177751
    url: https://access.redhat.com/errata/RHSA-2015:1945
    reference_id: RHSA-2015:1945
weaknesses: []
