vulnerability_id: VCID-2xe9-pbxb-aaap
aliases:
  - CVE-2020-8557
summary:
severities:
  - id: 610809
    reference_id: 931934
    scoring_system: cvssv3
    value: '5.5'
    scoring_elements: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
  - id: 610803
    reference_id: 931928
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 491920
    reference_id: 854906
    scoring_system: cvssv2
    value: '2.1'
    scoring_elements: AV:L/AC:L/Au:N/C:N/I:N/A:P
  - id: 491918
    reference_id: 854906
    scoring_system: cvssv3
    value: '5.5'
    scoring_elements: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
  - id: 610807
    reference_id: 931932
    scoring_system: rhas
    value: Important
    scoring_elements:
  - id: 610804
    reference_id: 931929
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 610808
    reference_id: 931933
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 610806
    reference_id: 931931
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 610330
    reference_id: 931585
    scoring_system: rhas
    value: Important
    scoring_elements:
  - id: 54823
    reference_id: 179943
    scoring_system: rhas
    value: Moderate
    scoring_elements:
  - id: 610805
    reference_id: 931930
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 931934
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2020-8557.json
    reference_id:
  - id: 854903
    url: https://github.com/kubernetes/kubernetes/issues/93032
    reference_id:
  - id: 854904
    url: https://groups.google.com/g/kubernetes-security-announce/c/cB_JUsYEKyY/m/vVSO61AhBwAJ
    reference_id:
  - id: 854905
    url: https://security.netapp.com/advisory/ntap-20200821-0002/
    reference_id:
  - id: 931928
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1835977
    reference_id: 1835977
  - id: 669448
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  - id: 854906
    url: https://nvd.nist.gov/vuln/detail/CVE-2020-8557
    reference_id: CVE-2020-8557
  - id: 931932
    url: https://access.redhat.com/errata/RHSA-2020:3519
    reference_id: RHSA-2020:3519
  - id: 931929
    url: https://access.redhat.com/errata/RHSA-2020:3520
    reference_id: RHSA-2020:3520
  - id: 931933
    url: https://access.redhat.com/errata/RHSA-2020:3579
    reference_id: RHSA-2020:3579
  - id: 931931
    url: https://access.redhat.com/errata/RHSA-2020:3580
    reference_id: RHSA-2020:3580
  - id: 931585
    url: https://access.redhat.com/errata/RHSA-2020:3808
    reference_id: RHSA-2020:3808
  - id: 179943
    url: https://access.redhat.com/errata/RHSA-2020:3809
    reference_id: RHSA-2020:3809
  - id: 931930
    url: https://access.redhat.com/errata/RHSA-2021:3915
    reference_id: RHSA-2021:3915
weaknesses: []
