vulnerability_id: VCID-h94n-73z9-aaak
aliases:
  - CVE-2019-11243
summary: In Kubernetes v1.12.0-v1.12.4 and v1.13.0, the rest.AnonymousClientConfig() method
  returns a copy of the provided config, with credentials removed (bearer token, username/password,
  and client certificate/key data). In the affected versions, rest.AnonymousClientConfig() did
  not effectively clear service account credentials loaded using rest.InClusterConfig()
severities:
  - id: 55713
    reference_id: 181074
    scoring_system: cvssv3
    value: '3.1'
    scoring_elements: CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N
  - id: 55712
    reference_id: 181073
    scoring_system: rhbs
    value: low
    scoring_elements:
  - id: 371355
    reference_id: 769710
    scoring_system: cvssv2
    value: '4.3'
    scoring_elements: AV:N/AC:M/Au:N/C:P/I:N/A:N
  - id: 371353
    reference_id: 769710
    scoring_system: cvssv3
    value: '8.1'
    scoring_elements: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H
references:
  - id: 181074
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2019-11243.json
    reference_id:
  - id: 769708
    url: https://github.com/kubernetes/kubernetes/issues/76797
    reference_id:
  - id: 769709
    url: https://security.netapp.com/advisory/ntap-20190509-0002/
    reference_id:
  - id: 769707
    url: http://www.securityfocus.com/bid/108053
    reference_id:
  - id: 181073
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1703218
    reference_id: 1703218
  - id: 669448
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:*:*:*:*:*:*:*:*
  - id: 769711
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:kubernetes:kubernetes:1.13.0:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:kubernetes:kubernetes:1.13.0:*:*:*:*:*:*:*
  - id: 722774
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:netapp:trident:-:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:netapp:trident:-:*:*:*:*:*:*:*
  - id: 769710
    url: https://nvd.nist.gov/vuln/detail/CVE-2019-11243
    reference_id: CVE-2019-11243
weaknesses: []
