affected_purls: []
aliases:
- CVE-2015-7528
fixed_purl:
- pkg:deb/debian/kubernetes@0?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=sid
references: []
severities: []
summary: Kubernetes before 1.2.0-alpha.5 allows remote attackers to read arbitrary
  pod logs via a container name.
vulnerability_id: VCID-u8ue-xa36-aaar
weaknesses: []
