affected_purls: []
aliases:
- CVE-2016-1906
fixed_purl:
- pkg:deb/debian/kubernetes@0?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=sid
references: []
severities: []
summary: Openshift allows remote attackers to gain privileges by updating a build
  configuration that was created with an allowed type to a type that is not allowed.
vulnerability_id: VCID-1teq-9hjv-aaan
weaknesses: []
