affected_purls: []
aliases:
- CVE-2018-1002105
fixed_purl:
- pkg:deb/debian/kubernetes@1.17.4-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=sid
references:
- id: 127745
  reference_id: '915828'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915828
severities: []
summary: In all Kubernetes versions prior to v1.10.11, v1.11.5, and v1.12.3, incorrect
  handling of error responses to proxied upgrade requests in the kube-apiserver allowed
  specially crafted requests to establish a connection through the Kubernetes API
  server to backend servers, then send arbitrary requests over the same connection
  directly to the backend, authenticated with the Kubernetes API server's TLS credentials
  used to establish the backend connection.
vulnerability_id: VCID-mmgh-kz5m-aaar
weaknesses: []
