affected_purls: []
aliases:
- CVE-2019-11248
fixed_purl:
- pkg:deb/debian/kubernetes@1.17.4-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=sid
references:
- id: 128459
  reference_id: '934182'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934182
severities: []
summary: The debugging endpoint /debug/pprof is exposed over the unauthenticated Kubelet
  healthz port. The go pprof endpoint is exposed over the Kubelet's healthz port.
  This debugging endpoint can potentially leak sensitive information such as internal
  Kubelet memory addresses and configuration, or for limited denial of service. Versions
  prior to 1.15.0, 1.14.4, 1.13.8, and 1.12.10 are affected. The issue is of medium
  severity, but not exposed by the default configuration.
vulnerability_id: VCID-ehky-afh6-aaaa
weaknesses: []
