affected_purls: []
aliases:
- CVE-2020-8566
fixed_purl:
- pkg:deb/debian/kubernetes@1.19.3-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=sid
references:
- id: 129535
  reference_id: '972341'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972341
severities: []
summary: In Kubernetes clusters using Ceph RBD as a storage provisioner, with logging
  level of at least 4, Ceph RBD admin secrets can be written to logs. This occurs
  in kube-controller-manager's logs during provisioning of Ceph RBD persistent claims.
  This affects < v1.19.3, < v1.18.10, < v1.17.13.
vulnerability_id: VCID-5m3r-qs8z-aaab
weaknesses: []
