affected_purls: []
aliases:
- CVE-2020-8551
fixed_purl:
- pkg:deb/debian/kubernetes@1.17.4-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1?distro=sid
- pkg:deb/debian/kubernetes@1.20.5%2Breally1.20.2-1.1?distro=sid
references: []
severities: []
summary: The Kubelet component in versions 1.15.0-1.15.9, 1.16.0-1.16.6, and 1.17.0-1.17.2
  has been found to be vulnerable to a denial of service attack via the kubelet API,
  including the unauthenticated HTTP read-only API typically served on port 10255,
  and the authenticated HTTPS API typically served on port 10250.
vulnerability_id: VCID-md2f-g6rh-aaaj
weaknesses: []
