pacakge: pkg:deb/debian/xfce4-settings
versions:
  - purl: pkg:deb/debian/xfce4-settings@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
  - purl: pkg:deb/debian/xfce4-settings@4.12.4-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/xfce4-settings@4.12.4-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/xfce4-settings@4.16.0-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/xfce4-settings@4.16.0-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/xfce4-settings@4.16.0-1%2Bdeb11u1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
  - purl: pkg:deb/debian/xfce4-settings@4.16.3-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/xfce4-settings@4.16.3-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/xfce4-settings@4.16.4-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
  - purl: pkg:deb/debian/xfce4-settings@4.16.4-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
  - purl: pkg:deb/debian/xfce4-settings@4.16.5-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
  - purl: pkg:deb/debian/xfce4-settings@4.18.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
  - purl: pkg:deb/debian/xfce4-settings@4.18.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
  - purl: pkg:deb/debian/xfce4-settings@4.18.2-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ptzc-pu8s-aaam
