package: pkg:deb/debian/libconfig-model-perl
versions:
  - purl: pkg:deb/debian/libconfig-model-perl@2.097-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.097-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.097-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.097-2?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.133-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.133-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.133-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.133-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.141-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.141-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.141-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.141-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.150-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.150-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.150-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.150-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.151-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.151-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.152-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
  - purl: pkg:deb/debian/libconfig-model-perl@2.152-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-5gcx-j1fr-aaab
      - VCID-qujy-gwwf-aaaf
