affected_purls: []
aliases:
- CVE-2020-25636
fixed_purl:
- pkg:deb/debian/ansible@0?distro=sid
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
references: []
severities: []
summary: A flaw was found in Ansible Base when using the aws_ssm connection plugin
  as there is no namespace separation for file transfers. Files are written directly
  to the root bucket, making possible to have collisions when running multiple ansible
  processes. This issue affects mainly the service availability.
vulnerability_id: VCID-3n3q-actw-aaah
weaknesses: []
