affected_purls:
- pkg:pypi/ansible@1.0
- pkg:pypi/ansible@1.1
- pkg:pypi/ansible@1.2
- pkg:pypi/ansible@1.2.1
- pkg:pypi/ansible@1.2.2
- pkg:pypi/ansible@1.2.3
- pkg:pypi/ansible@1.3.0
- pkg:pypi/ansible@1.3.1
- pkg:pypi/ansible@1.3.2
- pkg:pypi/ansible@1.3.3
- pkg:pypi/ansible@1.3.4
- pkg:pypi/ansible@1.4
- pkg:pypi/ansible@1.4.1
- pkg:pypi/ansible@1.4.2
- pkg:pypi/ansible@1.4.3
- pkg:pypi/ansible@1.4.4
- pkg:pypi/ansible@1.4.5
- pkg:pypi/ansible@1.5
- pkg:pypi/ansible@1.5.1
- pkg:pypi/ansible@1.5.2
- pkg:pypi/ansible@1.5.3
- pkg:pypi/ansible@1.5.4
- pkg:pypi/ansible@1.5.5
- pkg:pypi/ansible@1.6
- pkg:pypi/ansible@1.6.1
- pkg:pypi/ansible@1.6.10
- pkg:pypi/ansible@1.6.2
- pkg:pypi/ansible@1.6.3
- pkg:pypi/ansible@1.6.4
- pkg:pypi/ansible@1.6.5
- pkg:pypi/ansible@1.6.6
- pkg:pypi/ansible@1.6.7
- pkg:pypi/ansible@1.6.8
- pkg:pypi/ansible@1.6.9
- pkg:pypi/ansible@1.7
- pkg:pypi/ansible@1.7.1
- pkg:pypi/ansible@1.7.2
- pkg:pypi/ansible@1.8
- pkg:pypi/ansible@1.8.1
- pkg:pypi/ansible@1.8.2
- pkg:pypi/ansible@1.8.3
- pkg:pypi/ansible@1.8.4
- pkg:pypi/ansible@1.9.0.1
- pkg:pypi/ansible@1.9.1
aliases:
- CVE-2015-3908
- GHSA-w64c-pxjj-h866
fixed_purl:
- pkg:deb/debian/ansible@1.9.2%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@1.9.2
references:
- id: 137639
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-updates/2015-07/msg00051.html
- id: 137640
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-updates/2015-08/msg00029.html
- id: 177450
  reference_id: ''
  url: https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#192-dancing-in-the-street---jun-26-2015
- id: 137638
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html
- id: 137641
  reference_id: ''
  url: http://www.ansible.com/security
- id: 137642
  reference_id: ''
  url: http://www.openwall.com/lists/oss-security/2015/07/14/4
- id: 137636
  reference_id: CVE-2015-3908
  url: https://nvd.nist.gov/vuln/detail/CVE-2015-3908
- id: 137637
  reference_id: GHSA-w64c-pxjj-h866
  url: https://github.com/advisories/GHSA-w64c-pxjj-h866
severities:
- id: 18913
  reference_id: 137637
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: Ansible before 1.9.2 does not verify that the server hostname matches a domain
  name in the subject's Common Name (CN) or subjectAltName field of the X.509 certificate,
  which allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid
  certificate.
vulnerability_id: VCID-7ksc-n14u-aaas
weaknesses: []
