affected_purls:
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1
- pkg:pypi/ansible@2.7.0
- pkg:pypi/ansible@2.7.1
- pkg:pypi/ansible@2.7.10
- pkg:pypi/ansible@2.7.11
- pkg:pypi/ansible@2.7.12
- pkg:pypi/ansible@2.7.13
- pkg:pypi/ansible@2.7.14
- pkg:pypi/ansible@2.7.15
- pkg:pypi/ansible@2.7.2
- pkg:pypi/ansible@2.7.3
- pkg:pypi/ansible@2.7.4
- pkg:pypi/ansible@2.7.5
- pkg:pypi/ansible@2.7.6
- pkg:pypi/ansible@2.7.7
- pkg:pypi/ansible@2.7.8
- pkg:pypi/ansible@2.7.9
- pkg:pypi/ansible@2.8.0
- pkg:pypi/ansible@2.8.1
- pkg:pypi/ansible@2.8.2
- pkg:pypi/ansible@2.8.3
- pkg:pypi/ansible@2.8.4
- pkg:pypi/ansible@2.8.5
- pkg:pypi/ansible@2.8.6
- pkg:pypi/ansible@2.8.7
- pkg:pypi/ansible@2.9.0
- pkg:pypi/ansible@2.9.1
- pkg:pypi/ansible@2.9.2
aliases:
- CVE-2019-14905
- GHSA-frxj-5j27-f8rf
fixed_purl:
- pkg:deb/debian/ansible@2.9.16%2Bdfsg-1~bpo10%2B2
- pkg:pypi/ansible@2.7.16
- pkg:pypi/ansible@2.8.8
- pkg:pypi/ansible@2.9.3
references:
- id: 146711
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html
- id: 146712
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html
- id: 148090
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2020:0216
- id: 148091
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2020:0218
- id: 148092
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14905
- id: 148093
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5BNCYPQ4BY5QHBCJOAOPANB5FHATW2BR/
- id: 148089
  reference_id: CVE-2019-14905
  url: https://nvd.nist.gov/vuln/detail/CVE-2019-14905
- id: 148094
  reference_id: GHSA-frxj-5j27-f8rf
  url: https://github.com/advisories/GHSA-frxj-5j27-f8rf
severities:
- id: 20863
  reference_id: 148094
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: A vulnerability was found in Ansible Engine versions 2.9.x before 2.9.3,
  2.8.x before 2.8.8, 2.7.x before 2.7.16 and earlier, where in Ansible's nxos_file_copy
  module can be used to copy files to a flash or bootflash on NXOS devices. Malicious
  code could craft the filename parameter to perform OS command injections. This could
  result in a loss of confidentiality of the system among other issues.
vulnerability_id: VCID-jqda-3fj1-aaac
weaknesses: []
