affected_purls:
- pkg:pypi/ansible@2.3.0.0
- pkg:pypi/ansible@2.3.1.0
- pkg:pypi/ansible@2.3.2.0
- pkg:pypi/ansible@2.4.0.0
aliases:
- CVE-2017-7550
- GHSA-588w-w6mv-3cw5
fixed_purl:
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.4.2.0%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.3.3.0
- pkg:pypi/ansible@2.4.1.0
references:
- id: 142848
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2017:2966
- id: 142849
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1473645
- id: 142847
  reference_id: ''
  url: https://github.com/ansible/ansible/issues/30874
- id: 142850
  reference_id: CVE-2017-7550
  url: https://access.redhat.com/security/cve/CVE-2017-7550
- id: 142846
  reference_id: CVE-2017-7550
  url: https://nvd.nist.gov/vuln/detail/CVE-2017-7550
- id: 142851
  reference_id: GHSA-588w-w6mv-3cw5
  url: https://github.com/advisories/GHSA-588w-w6mv-3cw5
severities:
- id: 19896
  reference_id: 142851
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: CRITICAL
summary: A flaw was found in the way Ansible (2.3.x before 2.3.3, and 2.4.x before
  2.4.1) passed certain parameters to the jenkins_plugin module. Remote attackers
  could use this flaw to expose sensitive information from a remote host's logs. This
  flaw was fixed by not allowing passwords to be specified in the "params" argument,
  and noting this in the module documentation.
vulnerability_id: VCID-9a4j-qp5g-aaac
weaknesses: []
