affected_purls:
- pkg:pypi/ansible@1.0
- pkg:pypi/ansible@1.1
- pkg:pypi/ansible@1.2
- pkg:pypi/ansible@1.2.1
- pkg:pypi/ansible@1.2.2
- pkg:pypi/ansible@1.2.3
- pkg:pypi/ansible@1.3.0
- pkg:pypi/ansible@1.3.1
- pkg:pypi/ansible@1.3.2
- pkg:pypi/ansible@1.3.3
- pkg:pypi/ansible@1.3.4
- pkg:pypi/ansible@1.4
- pkg:pypi/ansible@1.4.1
- pkg:pypi/ansible@1.4.2
- pkg:pypi/ansible@1.4.3
- pkg:pypi/ansible@1.4.4
- pkg:pypi/ansible@1.4.5
- pkg:pypi/ansible@1.5
- pkg:pypi/ansible@1.5.1
- pkg:pypi/ansible@1.5.2
- pkg:pypi/ansible@1.5.3
- pkg:pypi/ansible@1.5.4
- pkg:pypi/ansible@1.5.5
- pkg:pypi/ansible@1.6
- pkg:pypi/ansible@1.6.1
- pkg:pypi/ansible@1.6.10
- pkg:pypi/ansible@1.6.2
- pkg:pypi/ansible@1.6.3
- pkg:pypi/ansible@1.6.4
- pkg:pypi/ansible@1.6.5
- pkg:pypi/ansible@1.6.6
- pkg:pypi/ansible@1.6.7
- pkg:pypi/ansible@1.6.8
- pkg:pypi/ansible@1.6.9
- pkg:pypi/ansible@1.7
- pkg:pypi/ansible@1.7.1
- pkg:pypi/ansible@1.7.2
- pkg:pypi/ansible@1.8
- pkg:pypi/ansible@1.8.1
- pkg:pypi/ansible@1.8.2
- pkg:pypi/ansible@1.8.3
- pkg:pypi/ansible@1.8.4
- pkg:pypi/ansible@1.9.0.1
- pkg:pypi/ansible@1.9.1
- pkg:pypi/ansible@1.9.2
- pkg:pypi/ansible@1.9.3
- pkg:pypi/ansible@1.9.4
- pkg:pypi/ansible@1.9.5
- pkg:pypi/ansible@1.9.6
- pkg:pypi/ansible@2.0.0.0
- pkg:pypi/ansible@2.0.0.1
- pkg:pypi/ansible@2.0.0.2
- pkg:pypi/ansible@2.0.1.0
- pkg:pypi/ansible@2.0.2.0
- pkg:pypi/ansible@2.1.0.0
- pkg:pypi/ansible@2.1.1.0
- pkg:pypi/ansible@2.1.2.0
- pkg:pypi/ansible@2.1.3.0
- pkg:pypi/ansible@2.1.4.0
- pkg:pypi/ansible@2.1.5.0
- pkg:pypi/ansible@2.1.6.0
- pkg:pypi/ansible@2.2.0.0
- pkg:pypi/ansible@2.2.1.0
- pkg:pypi/ansible@2.2.2.0
- pkg:pypi/ansible@2.2.3.0
- pkg:pypi/ansible@2.3.0.0
- pkg:pypi/ansible@2.3.1.0
- pkg:pypi/ansible@2.3.2.0
- pkg:pypi/ansible@2.3.3.0
- pkg:pypi/ansible@2.4.0.0
- pkg:pypi/ansible@2.4.1.0
- pkg:pypi/ansible@2.4.2.0
- pkg:pypi/ansible@2.4.3.0
- pkg:pypi/ansible@2.4.4.0
- pkg:pypi/ansible@2.4.5.0
- pkg:pypi/ansible@2.4.6.0
- pkg:pypi/ansible@2.5.0
- pkg:pypi/ansible@2.5.0a1
- pkg:pypi/ansible@2.5.0b1
- pkg:pypi/ansible@2.5.0b2
- pkg:pypi/ansible@2.5.0rc1
- pkg:pypi/ansible@2.5.0rc2
- pkg:pypi/ansible@2.5.0rc3
- pkg:pypi/ansible@2.5.1
- pkg:pypi/ansible@2.5.10
- pkg:pypi/ansible@2.5.11
- pkg:pypi/ansible@2.5.12
- pkg:pypi/ansible@2.5.13
- pkg:pypi/ansible@2.5.14
- pkg:pypi/ansible@2.5.2
- pkg:pypi/ansible@2.5.3
- pkg:pypi/ansible@2.5.4
- pkg:pypi/ansible@2.5.5
- pkg:pypi/ansible@2.5.6
- pkg:pypi/ansible@2.5.7
- pkg:pypi/ansible@2.5.8
- pkg:pypi/ansible@2.5.9
- pkg:pypi/ansible@2.6.0
- pkg:pypi/ansible@2.6.1
- pkg:pypi/ansible@2.6.10
- pkg:pypi/ansible@2.6.11
- pkg:pypi/ansible@2.6.12
- pkg:pypi/ansible@2.6.13
- pkg:pypi/ansible@2.6.2
- pkg:pypi/ansible@2.6.3
- pkg:pypi/ansible@2.6.4
- pkg:pypi/ansible@2.6.5
- pkg:pypi/ansible@2.6.6
- pkg:pypi/ansible@2.6.7
- pkg:pypi/ansible@2.6.8
- pkg:pypi/ansible@2.6.9
- pkg:pypi/ansible@2.7.0
- pkg:pypi/ansible@2.7.1
- pkg:pypi/ansible@2.7.2
- pkg:pypi/ansible@2.7.3
- pkg:pypi/ansible@2.7.4
- pkg:pypi/ansible@2.7.5
- pkg:pypi/ansible@2.7.6
- pkg:pypi/ansible@2.7.7
aliases:
- CVE-2019-3828
- GHSA-74vq-h4q8-x6jv
fixed_purl:
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.5.15
- pkg:pypi/ansible@2.6.14
- pkg:pypi/ansible@2.7.8
references:
- id: 182537
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3828
- id: 128885
  reference_id: '922537'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922537
- id: 149459
  reference_id: CVE-2019-3828
  url: https://nvd.nist.gov/vuln/detail/CVE-2019-3828
- id: 149460
  reference_id: GHSA-74vq-h4q8-x6jv
  url: https://github.com/advisories/GHSA-74vq-h4q8-x6jv
severities:
- id: 21091
  reference_id: 149460
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: Ansible fetch module before versions 2.5.15, 2.6.14, 2.7.8 has a path traversal
  vulnerability which allows copying and overwriting files outside of the specified
  destination in the local ansible controller host, by not restricting an absolute
  path.
vulnerability_id: VCID-krtk-sh6x-aaag
weaknesses: []
