affected_purls:
- pkg:pypi/ansible@1.0
- pkg:pypi/ansible@1.1
- pkg:pypi/ansible@1.2
- pkg:pypi/ansible@1.2.1
- pkg:pypi/ansible@1.2.2
- pkg:pypi/ansible@1.2.3
- pkg:pypi/ansible@1.3.0
- pkg:pypi/ansible@1.3.1
- pkg:pypi/ansible@1.3.2
- pkg:pypi/ansible@1.3.3
- pkg:pypi/ansible@1.3.4
- pkg:pypi/ansible@1.4
- pkg:pypi/ansible@1.4.1
- pkg:pypi/ansible@1.4.2
- pkg:pypi/ansible@1.4.3
- pkg:pypi/ansible@1.4.4
- pkg:pypi/ansible@1.4.5
- pkg:pypi/ansible@1.5
- pkg:pypi/ansible@1.5.1
- pkg:pypi/ansible@1.5.2
- pkg:pypi/ansible@1.5.3
- pkg:pypi/ansible@1.5.4
- pkg:pypi/ansible@1.5.5
- pkg:pypi/ansible@1.6
- pkg:pypi/ansible@1.6.1
- pkg:pypi/ansible@1.6.10
- pkg:pypi/ansible@1.6.2
- pkg:pypi/ansible@1.6.3
- pkg:pypi/ansible@1.6.4
- pkg:pypi/ansible@1.6.5
- pkg:pypi/ansible@1.6.6
- pkg:pypi/ansible@1.6.7
- pkg:pypi/ansible@1.6.8
- pkg:pypi/ansible@1.6.9
- pkg:pypi/ansible@1.7
- pkg:pypi/ansible@1.7.1
- pkg:pypi/ansible@1.7.2
- pkg:pypi/ansible@1.8
- pkg:pypi/ansible@1.8.1
- pkg:pypi/ansible@1.8.2
- pkg:pypi/ansible@1.8.3
- pkg:pypi/ansible@1.8.4
- pkg:pypi/ansible@1.9.0.1
- pkg:pypi/ansible@1.9.1
- pkg:pypi/ansible@1.9.2
- pkg:pypi/ansible@1.9.3
- pkg:pypi/ansible@1.9.4
- pkg:pypi/ansible@1.9.5
- pkg:pypi/ansible@1.9.6
- pkg:pypi/ansible@2.0.0.0
- pkg:pypi/ansible@2.0.0.1
- pkg:pypi/ansible@2.0.0.2
- pkg:pypi/ansible@2.0.1.0
- pkg:pypi/ansible@2.0.2.0
- pkg:pypi/ansible@2.1.0.0
- pkg:pypi/ansible@2.1.1.0
- pkg:pypi/ansible@2.1.2.0
- pkg:pypi/ansible@2.1.3.0
- pkg:pypi/ansible@2.1.4.0
- pkg:pypi/ansible@2.1.5.0
- pkg:pypi/ansible@2.1.6.0
- pkg:pypi/ansible@2.2.0.0
- pkg:pypi/ansible@2.2.1.0
- pkg:pypi/ansible@2.2.2.0
- pkg:pypi/ansible@2.2.3.0
- pkg:pypi/ansible@2.3.0.0
- pkg:pypi/ansible@2.3.1.0
- pkg:pypi/ansible@2.3.2.0
- pkg:pypi/ansible@2.3.3.0
- pkg:pypi/ansible@2.4.0.0
- pkg:pypi/ansible@2.4.1.0
- pkg:pypi/ansible@2.4.2.0
- pkg:pypi/ansible@2.4.3.0
- pkg:pypi/ansible@2.4.4.0
- pkg:pypi/ansible@2.4.5.0
- pkg:pypi/ansible@2.4.6.0
- pkg:pypi/ansible@2.5.0
- pkg:pypi/ansible@2.5.0a1
- pkg:pypi/ansible@2.5.0b1
- pkg:pypi/ansible@2.5.0b2
- pkg:pypi/ansible@2.5.0rc1
- pkg:pypi/ansible@2.5.0rc2
- pkg:pypi/ansible@2.5.0rc3
- pkg:pypi/ansible@2.5.1
- pkg:pypi/ansible@2.5.10
- pkg:pypi/ansible@2.5.11
- pkg:pypi/ansible@2.5.12
- pkg:pypi/ansible@2.5.13
- pkg:pypi/ansible@2.5.14
- pkg:pypi/ansible@2.5.15
- pkg:pypi/ansible@2.5.2
- pkg:pypi/ansible@2.5.3
- pkg:pypi/ansible@2.5.4
- pkg:pypi/ansible@2.5.5
- pkg:pypi/ansible@2.5.6
- pkg:pypi/ansible@2.5.7
- pkg:pypi/ansible@2.5.8
- pkg:pypi/ansible@2.5.9
- pkg:pypi/ansible@2.6.0
- pkg:pypi/ansible@2.6.0a1
- pkg:pypi/ansible@2.6.0a2
- pkg:pypi/ansible@2.6.0rc1
- pkg:pypi/ansible@2.6.0rc2
- pkg:pypi/ansible@2.6.0rc3
- pkg:pypi/ansible@2.6.0rc4
- pkg:pypi/ansible@2.6.0rc5
- pkg:pypi/ansible@2.6.1
- pkg:pypi/ansible@2.6.10
- pkg:pypi/ansible@2.6.11
- pkg:pypi/ansible@2.6.12
- pkg:pypi/ansible@2.6.13
- pkg:pypi/ansible@2.6.14
- pkg:pypi/ansible@2.6.15
- pkg:pypi/ansible@2.6.16
- pkg:pypi/ansible@2.6.17
- pkg:pypi/ansible@2.6.18
- pkg:pypi/ansible@2.6.19
- pkg:pypi/ansible@2.6.2
- pkg:pypi/ansible@2.6.20
- pkg:pypi/ansible@2.6.3
- pkg:pypi/ansible@2.6.4
- pkg:pypi/ansible@2.6.5
- pkg:pypi/ansible@2.6.6
- pkg:pypi/ansible@2.6.7
- pkg:pypi/ansible@2.6.8
- pkg:pypi/ansible@2.6.9
- pkg:pypi/ansible@2.7.0
- pkg:pypi/ansible@2.7.0a1
- pkg:pypi/ansible@2.7.0b1
- pkg:pypi/ansible@2.7.0.dev0
- pkg:pypi/ansible@2.7.0rc1
- pkg:pypi/ansible@2.7.0rc2
- pkg:pypi/ansible@2.7.0rc3
- pkg:pypi/ansible@2.7.0rc4
- pkg:pypi/ansible@2.7.1
- pkg:pypi/ansible@2.7.10
- pkg:pypi/ansible@2.7.11
- pkg:pypi/ansible@2.7.12
- pkg:pypi/ansible@2.7.13
- pkg:pypi/ansible@2.7.14
- pkg:pypi/ansible@2.7.15
- pkg:pypi/ansible@2.7.16
- pkg:pypi/ansible@2.7.2
- pkg:pypi/ansible@2.7.3
- pkg:pypi/ansible@2.7.4
- pkg:pypi/ansible@2.7.5
- pkg:pypi/ansible@2.7.6
- pkg:pypi/ansible@2.7.7
- pkg:pypi/ansible@2.7.8
- pkg:pypi/ansible@2.7.9
- pkg:pypi/ansible@2.8.0
- pkg:pypi/ansible@2.8.1
- pkg:pypi/ansible@2.8.10
- pkg:pypi/ansible@2.8.2
- pkg:pypi/ansible@2.8.3
- pkg:pypi/ansible@2.8.4
- pkg:pypi/ansible@2.8.5
- pkg:pypi/ansible@2.8.6
- pkg:pypi/ansible@2.8.7
- pkg:pypi/ansible@2.8.8
- pkg:pypi/ansible@2.8.9
- pkg:pypi/ansible@2.9.0
- pkg:pypi/ansible@2.9.1
- pkg:pypi/ansible@2.9.2
- pkg:pypi/ansible@2.9.3
- pkg:pypi/ansible@2.9.4
- pkg:pypi/ansible@2.9.5
- pkg:pypi/ansible@2.9.6
aliases:
- CVE-2020-1753
- GHSA-86hp-cj9j-33vv
fixed_purl:
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@2.9.16%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.7.17
- pkg:pypi/ansible@2.8.0a1
- pkg:pypi/ansible@2.8.11
- pkg:pypi/ansible@2.9.7
references:
- id: 152245
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1753
- id: 152244
  reference_id: ''
  url: https://github.com/ansible-collections/kubernetes/pull/51
- id: 150055
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DKPA4KC3OJSUFASUYMG66HKJE7ADNGFW/
- id: 150056
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MRRYUU5ZBLPBXCYG6CFP35D64NP2UB2S/
- id: 150057
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WQVOQD4VAIXXTVQAJKTN7NUGTJFE2PCB/
- id: 150058
  reference_id: ''
  url: https://security.gentoo.org/glsa/202006-11
- id: 146542
  reference_id: ''
  url: https://www.debian.org/security/2021/dsa-4950
- id: 152243
  reference_id: CVE-2020-1753
  url: https://nvd.nist.gov/vuln/detail/CVE-2020-1753
- id: 152246
  reference_id: GHSA-86hp-cj9j-33vv
  url: https://github.com/advisories/GHSA-86hp-cj9j-33vv
severities:
- id: 21704
  reference_id: 152246
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: A security flaw was found in Ansible Engine, all Ansible 2.7.x versions prior
  to 2.7.17, all Ansible 2.8.x versions prior to 2.8.11 and all Ansible 2.9.x versions
  prior to 2.9.7, when managing kubernetes using the k8s module. Sensitive parameters
  such as passwords and tokens are passed to kubectl from the command line, not using
  an environment variable or an input configuration file. This will disclose passwords
  and tokens from process list and no_log directive from debug module would not have
  any effect making these secrets being disclosed on stdout and log files.
vulnerability_id: VCID-f8u2-zbkm-aaam
weaknesses: []
