affected_purls:
- pkg:pypi/ansible@2.0.0.0
- pkg:pypi/ansible@2.0.0.1
- pkg:pypi/ansible@2.0.0.2
- pkg:pypi/ansible@2.0.1.0
- pkg:pypi/ansible@2.0.2.0
- pkg:pypi/ansible@2.1.0.0
- pkg:pypi/ansible@2.1.1.0
- pkg:pypi/ansible@2.1.2.0
- pkg:pypi/ansible@2.1.3.0
- pkg:pypi/ansible@2.1.4.0
- pkg:pypi/ansible@2.1.5.0
- pkg:pypi/ansible@2.1.6.0
- pkg:pypi/ansible@2.2.0.0
- pkg:pypi/ansible@2.2.1.0
- pkg:pypi/ansible@2.2.2.0
- pkg:pypi/ansible@2.2.3.0
- pkg:pypi/ansible@2.3.0.0
- pkg:pypi/ansible@2.3.1.0
- pkg:pypi/ansible@2.3.2.0
- pkg:pypi/ansible@2.3.3.0
- pkg:pypi/ansible@2.4.0.0
- pkg:pypi/ansible@2.4.1.0
- pkg:pypi/ansible@2.4.2.0
- pkg:pypi/ansible@2.4.3.0
- pkg:pypi/ansible@2.4.4.0
- pkg:pypi/ansible@2.4.5.0
- pkg:pypi/ansible@2.4.6.0
- pkg:pypi/ansible@2.5.0
- pkg:pypi/ansible@2.5.0a1
- pkg:pypi/ansible@2.5.0b1
- pkg:pypi/ansible@2.5.0b2
- pkg:pypi/ansible@2.5.0rc1
- pkg:pypi/ansible@2.5.0rc2
- pkg:pypi/ansible@2.5.0rc3
- pkg:pypi/ansible@2.5.1
- pkg:pypi/ansible@2.5.10
- pkg:pypi/ansible@2.5.11
- pkg:pypi/ansible@2.5.12
- pkg:pypi/ansible@2.5.13
- pkg:pypi/ansible@2.5.14
- pkg:pypi/ansible@2.5.15
- pkg:pypi/ansible@2.5.2
- pkg:pypi/ansible@2.5.3
- pkg:pypi/ansible@2.5.4
- pkg:pypi/ansible@2.5.5
- pkg:pypi/ansible@2.5.6
- pkg:pypi/ansible@2.5.7
- pkg:pypi/ansible@2.5.8
- pkg:pypi/ansible@2.5.9
- pkg:pypi/ansible@2.6.0
- pkg:pypi/ansible@2.6.0a1
- pkg:pypi/ansible@2.6.0a2
- pkg:pypi/ansible@2.6.0rc1
- pkg:pypi/ansible@2.6.0rc2
- pkg:pypi/ansible@2.6.0rc3
- pkg:pypi/ansible@2.6.0rc4
- pkg:pypi/ansible@2.6.0rc5
- pkg:pypi/ansible@2.6.1
- pkg:pypi/ansible@2.6.10
- pkg:pypi/ansible@2.6.11
- pkg:pypi/ansible@2.6.12
- pkg:pypi/ansible@2.6.13
- pkg:pypi/ansible@2.6.14
- pkg:pypi/ansible@2.6.15
- pkg:pypi/ansible@2.6.16
- pkg:pypi/ansible@2.6.17
- pkg:pypi/ansible@2.6.18
- pkg:pypi/ansible@2.6.19
- pkg:pypi/ansible@2.6.2
- pkg:pypi/ansible@2.6.3
- pkg:pypi/ansible@2.6.4
- pkg:pypi/ansible@2.6.5
- pkg:pypi/ansible@2.6.6
- pkg:pypi/ansible@2.6.7
- pkg:pypi/ansible@2.6.8
- pkg:pypi/ansible@2.6.9
- pkg:pypi/ansible@2.7.0
- pkg:pypi/ansible@2.7.0a1
- pkg:pypi/ansible@2.7.0b1
- pkg:pypi/ansible@2.7.0.dev0
- pkg:pypi/ansible@2.7.0rc1
- pkg:pypi/ansible@2.7.0rc2
- pkg:pypi/ansible@2.7.0rc3
- pkg:pypi/ansible@2.7.0rc4
- pkg:pypi/ansible@2.7.1
- pkg:pypi/ansible@2.7.10
- pkg:pypi/ansible@2.7.11
- pkg:pypi/ansible@2.7.12
- pkg:pypi/ansible@2.7.13
- pkg:pypi/ansible@2.7.2
- pkg:pypi/ansible@2.7.3
- pkg:pypi/ansible@2.7.4
- pkg:pypi/ansible@2.7.5
- pkg:pypi/ansible@2.7.6
- pkg:pypi/ansible@2.7.7
- pkg:pypi/ansible@2.7.8
- pkg:pypi/ansible@2.7.9
- pkg:pypi/ansible@2.8.0
- pkg:pypi/ansible@2.8.0a1
- pkg:pypi/ansible@2.8.0b1
- pkg:pypi/ansible@2.8.0rc1
- pkg:pypi/ansible@2.8.0rc2
- pkg:pypi/ansible@2.8.0rc3
- pkg:pypi/ansible@2.8.1
- pkg:pypi/ansible@2.8.2
- pkg:pypi/ansible@2.8.3
- pkg:pypi/ansible@2.8.4
- pkg:pypi/ansible@2.8.5
aliases:
- CVE-2019-14846
fixed_purl:
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@2.8.6%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.9.0b1
references:
- id: 182403
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14846
- id: 128656
  reference_id: '942188'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942188
- id: 182402
  reference_id: CVE-2019-14846
  url: https://nvd.nist.gov/vuln/detail/CVE-2019-14846
severities: []
summary: In Ansible, all Ansible Engine versions up to ansible-engine 2.8.5, ansible-engine
  2.7.13, ansible-engine 2.6.19, were logging at the DEBUG level which lead to a disclosure
  of credentials if a plugin used a library that logged credentials at the DEBUG level.
  This flaw does not affect Ansible modules, as those are executed in a separate process.
vulnerability_id: VCID-anjr-f42a-aaaa
weaknesses: []
