affected_purls:
- pkg:pypi/ansible@1.0
- pkg:pypi/ansible@1.1
- pkg:pypi/ansible@1.2
- pkg:pypi/ansible@1.2.1
- pkg:pypi/ansible@1.2.2
- pkg:pypi/ansible@1.2.3
- pkg:pypi/ansible@1.3.0
- pkg:pypi/ansible@1.3.1
- pkg:pypi/ansible@1.3.2
- pkg:pypi/ansible@1.3.3
- pkg:pypi/ansible@1.3.4
- pkg:pypi/ansible@1.4
- pkg:pypi/ansible@1.4.1
- pkg:pypi/ansible@1.4.2
- pkg:pypi/ansible@1.4.3
- pkg:pypi/ansible@1.4.4
- pkg:pypi/ansible@1.4.5
- pkg:pypi/ansible@1.5
- pkg:pypi/ansible@1.5.1
- pkg:pypi/ansible@1.5.2
- pkg:pypi/ansible@1.5.3
- pkg:pypi/ansible@1.5.4
- pkg:pypi/ansible@1.5.5
- pkg:pypi/ansible@1.6
- pkg:pypi/ansible@1.6.1
- pkg:pypi/ansible@1.6.10
- pkg:pypi/ansible@1.6.2
- pkg:pypi/ansible@1.6.3
- pkg:pypi/ansible@1.6.4
- pkg:pypi/ansible@1.6.5
- pkg:pypi/ansible@1.6.6
- pkg:pypi/ansible@1.6.7
- pkg:pypi/ansible@1.6.8
- pkg:pypi/ansible@1.6.9
- pkg:pypi/ansible@1.7
- pkg:pypi/ansible@1.7.1
- pkg:pypi/ansible@1.7.2
- pkg:pypi/ansible@1.8
- pkg:pypi/ansible@1.8.1
- pkg:pypi/ansible@1.8.2
- pkg:pypi/ansible@1.8.3
- pkg:pypi/ansible@1.8.4
- pkg:pypi/ansible@1.9.0.1
- pkg:pypi/ansible@1.9.1
- pkg:pypi/ansible@1.9.2
- pkg:pypi/ansible@1.9.3
- pkg:pypi/ansible@1.9.4
- pkg:pypi/ansible@1.9.5
- pkg:pypi/ansible@1.9.6
- pkg:pypi/ansible@2.0.0.0
- pkg:pypi/ansible@2.0.0.1
- pkg:pypi/ansible@2.0.0.2
- pkg:pypi/ansible@2.0.1.0
- pkg:pypi/ansible@2.0.2.0
- pkg:pypi/ansible@2.1.0.0
- pkg:pypi/ansible@2.10.0
- pkg:pypi/ansible@2.10.1
- pkg:pypi/ansible@2.10.2
- pkg:pypi/ansible@2.10.3
- pkg:pypi/ansible@2.10.4
- pkg:pypi/ansible@2.10.5
- pkg:pypi/ansible@2.10.6
- pkg:pypi/ansible@2.1.1.0
- pkg:pypi/ansible@2.1.2.0
- pkg:pypi/ansible@2.1.3.0
- pkg:pypi/ansible@2.1.4.0
- pkg:pypi/ansible@2.1.5.0
- pkg:pypi/ansible@2.1.6.0
- pkg:pypi/ansible@2.2.0.0
- pkg:pypi/ansible@2.2.1.0
- pkg:pypi/ansible@2.2.2.0
- pkg:pypi/ansible@2.2.3.0
- pkg:pypi/ansible@2.3.0.0
- pkg:pypi/ansible@2.3.1.0
- pkg:pypi/ansible@2.3.2.0
- pkg:pypi/ansible@2.3.3.0
- pkg:pypi/ansible@2.4.0.0
- pkg:pypi/ansible@2.4.1.0
- pkg:pypi/ansible@2.4.2.0
- pkg:pypi/ansible@2.4.3.0
- pkg:pypi/ansible@2.4.4.0
- pkg:pypi/ansible@2.4.5.0
- pkg:pypi/ansible@2.4.6.0
- pkg:pypi/ansible@2.5.0
- pkg:pypi/ansible@2.5.0a1
- pkg:pypi/ansible@2.5.0b1
- pkg:pypi/ansible@2.5.0b2
- pkg:pypi/ansible@2.5.0rc1
- pkg:pypi/ansible@2.5.0rc2
- pkg:pypi/ansible@2.5.0rc3
- pkg:pypi/ansible@2.5.1
- pkg:pypi/ansible@2.5.10
- pkg:pypi/ansible@2.5.11
- pkg:pypi/ansible@2.5.12
- pkg:pypi/ansible@2.5.13
- pkg:pypi/ansible@2.5.14
- pkg:pypi/ansible@2.5.15
- pkg:pypi/ansible@2.5.2
- pkg:pypi/ansible@2.5.3
- pkg:pypi/ansible@2.5.4
- pkg:pypi/ansible@2.5.5
- pkg:pypi/ansible@2.5.6
- pkg:pypi/ansible@2.5.7
- pkg:pypi/ansible@2.5.8
- pkg:pypi/ansible@2.5.9
- pkg:pypi/ansible@2.6.0
- pkg:pypi/ansible@2.6.0a1
- pkg:pypi/ansible@2.6.0a2
- pkg:pypi/ansible@2.6.0rc1
- pkg:pypi/ansible@2.6.0rc2
- pkg:pypi/ansible@2.6.0rc3
- pkg:pypi/ansible@2.6.0rc4
- pkg:pypi/ansible@2.6.0rc5
- pkg:pypi/ansible@2.6.1
- pkg:pypi/ansible@2.6.10
- pkg:pypi/ansible@2.6.11
- pkg:pypi/ansible@2.6.12
- pkg:pypi/ansible@2.6.13
- pkg:pypi/ansible@2.6.14
- pkg:pypi/ansible@2.6.15
- pkg:pypi/ansible@2.6.16
- pkg:pypi/ansible@2.6.17
- pkg:pypi/ansible@2.6.18
- pkg:pypi/ansible@2.6.19
- pkg:pypi/ansible@2.6.2
- pkg:pypi/ansible@2.6.20
- pkg:pypi/ansible@2.6.3
- pkg:pypi/ansible@2.6.4
- pkg:pypi/ansible@2.6.5
- pkg:pypi/ansible@2.6.6
- pkg:pypi/ansible@2.6.7
- pkg:pypi/ansible@2.6.8
- pkg:pypi/ansible@2.6.9
- pkg:pypi/ansible@2.7.0
- pkg:pypi/ansible@2.7.0a1
- pkg:pypi/ansible@2.7.0b1
- pkg:pypi/ansible@2.7.0.dev0
- pkg:pypi/ansible@2.7.0rc1
- pkg:pypi/ansible@2.7.0rc2
- pkg:pypi/ansible@2.7.0rc3
- pkg:pypi/ansible@2.7.0rc4
- pkg:pypi/ansible@2.7.1
- pkg:pypi/ansible@2.7.10
- pkg:pypi/ansible@2.7.11
- pkg:pypi/ansible@2.7.12
- pkg:pypi/ansible@2.7.13
- pkg:pypi/ansible@2.7.14
- pkg:pypi/ansible@2.7.15
- pkg:pypi/ansible@2.7.16
- pkg:pypi/ansible@2.7.17
- pkg:pypi/ansible@2.7.18
- pkg:pypi/ansible@2.7.2
- pkg:pypi/ansible@2.7.3
- pkg:pypi/ansible@2.7.4
- pkg:pypi/ansible@2.7.5
- pkg:pypi/ansible@2.7.6
- pkg:pypi/ansible@2.7.7
- pkg:pypi/ansible@2.7.8
- pkg:pypi/ansible@2.7.9
- pkg:pypi/ansible@2.8.0
- pkg:pypi/ansible@2.8.0a1
- pkg:pypi/ansible@2.8.0b1
- pkg:pypi/ansible@2.8.0rc1
- pkg:pypi/ansible@2.8.0rc2
- pkg:pypi/ansible@2.8.0rc3
- pkg:pypi/ansible@2.8.1
- pkg:pypi/ansible@2.8.10
- pkg:pypi/ansible@2.8.11
- pkg:pypi/ansible@2.8.12
- pkg:pypi/ansible@2.8.13
- pkg:pypi/ansible@2.8.14
- pkg:pypi/ansible@2.8.15
- pkg:pypi/ansible@2.8.16
- pkg:pypi/ansible@2.8.16rc1
- pkg:pypi/ansible@2.8.17
- pkg:pypi/ansible@2.8.17rc1
- pkg:pypi/ansible@2.8.18
- pkg:pypi/ansible@2.8.18rc1
- pkg:pypi/ansible@2.8.19rc1
- pkg:pypi/ansible@2.8.2
- pkg:pypi/ansible@2.8.3
- pkg:pypi/ansible@2.8.4
- pkg:pypi/ansible@2.8.5
- pkg:pypi/ansible@2.8.6
- pkg:pypi/ansible@2.8.7
- pkg:pypi/ansible@2.8.8
- pkg:pypi/ansible@2.8.9
- pkg:pypi/ansible@2.9.0
- pkg:pypi/ansible@2.9.1
- pkg:pypi/ansible@2.9.10
- pkg:pypi/ansible@2.9.11
- pkg:pypi/ansible@2.9.12
- pkg:pypi/ansible@2.9.13
- pkg:pypi/ansible@2.9.14
- pkg:pypi/ansible@2.9.14rc1
- pkg:pypi/ansible@2.9.15
- pkg:pypi/ansible@2.9.15rc1
- pkg:pypi/ansible@2.9.16
- pkg:pypi/ansible@2.9.16rc1
- pkg:pypi/ansible@2.9.17
- pkg:pypi/ansible@2.9.17rc1
- pkg:pypi/ansible@2.9.18rc1
- pkg:pypi/ansible@2.9.2
- pkg:pypi/ansible@2.9.3
- pkg:pypi/ansible@2.9.4
- pkg:pypi/ansible@2.9.5
- pkg:pypi/ansible@2.9.6
- pkg:pypi/ansible@2.9.7
- pkg:pypi/ansible@2.9.8
- pkg:pypi/ansible@2.9.9
aliases:
- CVE-2021-20228
- GHSA-5rrg-rr89-x9mv
fixed_purl:
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.10.7
- pkg:pypi/ansible@2.8.19
- pkg:pypi/ansible@2.9.18
- pkg:pypi/ansible@2.9.19rc1
references:
- id: 156691
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1925002
- id: 156687
  reference_id: ''
  url: https://github.com/ansible/ansible/pull/73487
- id: 156688
  reference_id: ''
  url: https://github.com/ansible/ansible/pull/73492
- id: 156689
  reference_id: ''
  url: https://github.com/ansible/ansible/pull/73493
- id: 156690
  reference_id: ''
  url: https://github.com/ansible/ansible/pull/73494
- id: 156693
  reference_id: ''
  url: https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2021-1.yaml
- id: 146542
  reference_id: ''
  url: https://www.debian.org/security/2021/dsa-4950
- id: 156686
  reference_id: CVE-2021-20228
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-20228
- id: 156692
  reference_id: GHSA-5rrg-rr89-x9mv
  url: https://github.com/advisories/GHSA-5rrg-rr89-x9mv
severities:
- id: 22613
  reference_id: 156692
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: A flaw was found in the Ansible Engine 2.9.18, where sensitive info is not
  masked by default and is not protected by the no_log feature when using the sub-option
  feature of the basic.py module. This flaw allows an attacker to obtain sensitive
  information. The highest threat from this vulnerability is to confidentiality.
vulnerability_id: VCID-87ct-ue4c-aaaj
weaknesses: []
