affected_purls:
- pkg:pypi/ansible@2.0.0.0
- pkg:pypi/ansible@2.4.0.0
- pkg:pypi/ansible@2.4.1.0
- pkg:pypi/ansible@2.4.2.0
- pkg:pypi/ansible@2.4.3.0
- pkg:pypi/ansible@2.4.4.0
- pkg:pypi/ansible@2.4.5.0
- pkg:pypi/ansible@2.4.6.0
- pkg:pypi/ansible@2.5.0
- pkg:pypi/ansible@2.5.0a1
- pkg:pypi/ansible@2.5.0b1
- pkg:pypi/ansible@2.5.0b2
- pkg:pypi/ansible@2.5.0rc1
- pkg:pypi/ansible@2.5.0rc2
- pkg:pypi/ansible@2.5.0rc3
- pkg:pypi/ansible@2.5.1
- pkg:pypi/ansible@2.5.2
- pkg:pypi/ansible@2.5.3
- pkg:pypi/ansible@2.5.4
- pkg:pypi/ansible@2.5.5
- pkg:pypi/ansible@2.5.6
- pkg:pypi/ansible@2.6.0
- pkg:pypi/ansible@2.6.0a1
- pkg:pypi/ansible@2.6.0a2
- pkg:pypi/ansible@2.6.0rc1
- pkg:pypi/ansible@2.6.0rc2
- pkg:pypi/ansible@2.6.0rc3
- pkg:pypi/ansible@2.6.0rc4
- pkg:pypi/ansible@2.6.0rc5
aliases:
- CVE-2018-10875
fixed_purl:
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.6.1%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.0.0.1
- pkg:pypi/ansible@2.6.1
references:
- id: 181679
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875
- id: 143705
  reference_id: ''
  url: http://www.securitytracker.com/id/1041396
- id: 181678
  reference_id: CVE-2018-10875
  url: https://nvd.nist.gov/vuln/detail/CVE-2018-10875
severities: []
summary: A flaw was found in ansible. ansible.cfg is read from the current working
  directory which can be altered to make it point to a plugin or a module path under
  the control of an attacker, thus allowing the attacker to execute arbitrary code.
vulnerability_id: VCID-cxjd-9r7q-aaaq
weaknesses: []
