affected_purls:
- pkg:pypi/ansible@2.8.0
- pkg:pypi/ansible@2.8.1
- pkg:pypi/ansible@2.8.2
- pkg:pypi/ansible@2.8.3
aliases:
- CVE-2019-10217
- GHSA-p75j-wc34-527c
fixed_purl:
- pkg:deb/debian/ansible@0?distro=sid
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@2.8.6%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.8.4
references:
- id: 146711
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html
- id: 146712
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html
- id: 146724
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10217
- id: 146722
  reference_id: ''
  url: https://github.com/ansible/ansible/issues/56269
- id: 146723
  reference_id: ''
  url: https://github.com/ansible/ansible/pull/59427
- id: 128414
  reference_id: '934128'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934128
- id: 146721
  reference_id: CVE-2019-10217
  url: https://nvd.nist.gov/vuln/detail/CVE-2019-10217
- id: 146725
  reference_id: GHSA-p75j-wc34-527c
  url: https://github.com/advisories/GHSA-p75j-wc34-527c
severities:
- id: 20624
  reference_id: 146725
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: A flaw was found in ansible 2.8.0 before 2.8.4. Fields managing sensitive
  data should be set as such by no_log feature. Some of these fields in GCP modules
  are not set properly. service_account_contents() which is common class for all gcp
  modules is not setting no_log to True. Any sensitive data managed by that function
  would be leak as an output when running ansible playbooks.
vulnerability_id: VCID-twz9-n235-aaaq
weaknesses: []
