package: pkg:deb/debian/debian-edu-config
versions:
  - purl: pkg:deb/debian/debian-edu-config@1.929%2Bdeb9u4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@1.929%2Bdeb9u4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@1.929%2Bdeb9u5?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@1.929%2Bdeb9u5?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u8?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u8?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u8?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.10.65%2Bdeb10u8?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.11.10?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.11.10?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.11.10?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.11.10?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
  - purl: pkg:deb/debian/debian-edu-config@2.11.56%2Bdeb11u3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.11.56%2Bdeb11u3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.11.56%2Bdeb11u3?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.11.56%2Bdeb11u3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.11.56%2Bdeb11u4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.11.56%2Bdeb11u4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.16?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.16?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.16?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.16?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.20?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.20?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.22?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.22?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.22?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.22?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.23?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.23?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.24?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.24?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.25?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.25?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.26?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.28?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.29?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.30?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.31?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
  - purl: pkg:deb/debian/debian-edu-config@2.12.32?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-mxyt-esn9-aaaj
      - VCID-uaaw-v8a6-aaar
