vulnerability_id: VCID-8283-5hs3-aaar
aliases:
  - CVE-2021-29622
summary:
severities:
  - id: 605108
    reference_id: 927755
    scoring_system: cvssv3
    value: '6.1'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
  - id: 605107
    reference_id: 927754
    scoring_system: rhbs
    value: medium
    scoring_elements:
  - id: 532257
    reference_id: 879213
    scoring_system: cvssv2
    value: '5.8'
    scoring_elements: AV:N/AC:M/Au:N/C:P/I:P/A:N
  - id: 532255
    reference_id: 879213
    scoring_system: cvssv3
    value: '6.1'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
  - id: 604100
    reference_id: 927019
    scoring_system: rhas
    value: Moderate
    scoring_elements:
references:
  - id: 927755
    url: https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-29622.json
    reference_id:
  - id: 879210
    url: https://github.com/prometheus/prometheus/releases/tag/v2.26.1
    reference_id:
  - id: 879211
    url: https://github.com/prometheus/prometheus/releases/tag/v2.27.1
    reference_id:
  - id: 879212
    url: https://github.com/prometheus/prometheus/security/advisories/GHSA-vx57-7f4q-fpc7
    reference_id:
  - id: 927754
    url: https://bugzilla.redhat.com/show_bug.cgi?id=1962718
    reference_id: '1962718'
  - id: 796099
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:prometheus:prometheus:*:*:*:*:*:*:*:*
    reference_id: cpe:2.3:a:prometheus:prometheus:*:*:*:*:*:*:*:*
  - id: 879214
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:prometheus:prometheus:2.27.0:-:*:*:*:*:*:*
    reference_id: cpe:2.3:a:prometheus:prometheus:2.27.0:-:*:*:*:*:*:*
  - id: 879215
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:prometheus:prometheus:2.27.0:rc0:*:*:*:*:*:*
    reference_id: cpe:2.3:a:prometheus:prometheus:2.27.0:rc0:*:*:*:*:*:*
  - id: 879213
    url: https://nvd.nist.gov/vuln/detail/CVE-2021-29622
    reference_id: CVE-2021-29622
  - id: 927019
    url: https://access.redhat.com/errata/RHSA-2021:2438
    reference_id: RHSA-2021:2438
weaknesses: []
