package: pkg:deb/ubuntu/libcgi-application-perl
versions:
  - purl: pkg:deb/ubuntu/libcgi-application-perl@3.22-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@3.31-0.1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.01-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.04-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.06-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.06-2
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.10-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.20-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.21-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.31-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.31-2
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.50-1
    affected_by_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/libcgi-application-perl@4.50-2
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-pcm3-3sdj-aaah
