package: pkg:deb/debian/golang-github-prometheus-client-golang
versions:
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.8.0-1?distro=stretch
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.8.0-1?distro=stretch
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1?distro=stretch
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1?distro=sid
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@0.9.0-1?distro=stretch
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.1-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.11.1-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=stretch
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=sid
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=stretch
    affected_by_vulnerabilities:
      - VCID-tzxf-ndv1-aaan
    fixing_vulnerabilities: []
