pacakge: pkg:deb/debian/libconfig-inifiles-perl
versions:
  - purl: pkg:deb/debian/libconfig-inifiles-perl@2.72-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@2.72-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@2.72-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@2.72-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@2.94-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@2.94-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000001-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000001-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000001-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000001-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000003-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000003-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000003-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000003-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
  - purl: pkg:deb/debian/libconfig-inifiles-perl@3.000003-2?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-qrea-bd58-aaaf
