pacakge: pkg:deb/ubuntu/fontconfig
versions:
  - purl: pkg:deb/ubuntu/fontconfig@2.10.1-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.10.1-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.10.1-0ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.10.2-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.10.2-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.10.92-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.10.92-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.10.93-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.0-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.0-0ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.0-0ubuntu4
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.0-0ubuntu4.1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.0-0ubuntu4.2
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/ubuntu/fontconfig@2.11.0-0ubuntu5
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu4
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu5
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu6
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu7
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu8
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.1-0ubuntu9
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.94-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.11.94-0ubuntu1.1
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
  - purl: pkg:deb/ubuntu/fontconfig@2.2.2-2ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.2.3-4ubuntu7
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu10
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu11
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu12
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu4
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu5
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu6
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu7
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu8
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1.1ubuntu9
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-1ubuntu4
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-7ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.3.2-7ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.4.1-2ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.4.1-2ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.4.2-1.2ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.4.2-1.2ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.4.2-1.2ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.4.2-1.2ubuntu4
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.4.2-1ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.5.0-2ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.5.0-2ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.5.0-2ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu10
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu11
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu12
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu13
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu4
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu5
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu6
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu7
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu8
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.6.0-1ubuntu9
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-2.1ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-2.1ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-2.1ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-2.2ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-2ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu3
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu4
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu5
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu6
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu7
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu8
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu9
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu9.1
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/fontconfig@2.8.0-3ubuntu9.2
    affected_by_vulnerabilities:
      - VCID-bu3p-rbd7-aaan
    fixing_vulnerabilities: []
