affected_purls:
- pkg:gem/dependabot-common@0.119.0
- pkg:gem/dependabot-common@0.119.0.beta1
- pkg:gem/dependabot-common@0.119.1
- pkg:gem/dependabot-common@0.119.2
- pkg:gem/dependabot-common@0.119.3
- pkg:gem/dependabot-common@0.119.4
- pkg:gem/dependabot-common@0.119.5
- pkg:gem/dependabot-common@0.119.6
- pkg:gem/dependabot-common@0.120.0
- pkg:gem/dependabot-common@0.120.1
- pkg:gem/dependabot-common@0.120.2
- pkg:gem/dependabot-common@0.120.3
- pkg:gem/dependabot-common@0.120.4
- pkg:gem/dependabot-common@0.120.5
- pkg:gem/dependabot-common@0.121.0
- pkg:gem/dependabot-common@0.121.1
- pkg:gem/dependabot-common@0.122.0
- pkg:gem/dependabot-common@0.122.1
- pkg:gem/dependabot-common@0.123.0
- pkg:gem/dependabot-common@0.123.1
- pkg:gem/dependabot-common@0.124.0
- pkg:gem/dependabot-common@0.124.1
- pkg:gem/dependabot-common@0.124.2
- pkg:gem/dependabot-common@0.124.3
- pkg:gem/dependabot-common@0.124.4
- pkg:gem/dependabot-common@0.124.5
- pkg:gem/dependabot-common@0.124.6
- pkg:gem/dependabot-common@0.124.7
- pkg:gem/dependabot-common@0.124.8
- pkg:gem/dependabot-common@0.125.0
- pkg:gem/dependabot-omnibus@0.119.0
- pkg:gem/dependabot-omnibus@0.119.0.beta1
- pkg:gem/dependabot-omnibus@0.119.1
- pkg:gem/dependabot-omnibus@0.119.2
- pkg:gem/dependabot-omnibus@0.119.3
- pkg:gem/dependabot-omnibus@0.119.4
- pkg:gem/dependabot-omnibus@0.119.5
- pkg:gem/dependabot-omnibus@0.119.6
- pkg:gem/dependabot-omnibus@0.120.0
- pkg:gem/dependabot-omnibus@0.120.1
- pkg:gem/dependabot-omnibus@0.120.2
- pkg:gem/dependabot-omnibus@0.120.3
- pkg:gem/dependabot-omnibus@0.120.4
- pkg:gem/dependabot-omnibus@0.120.5
- pkg:gem/dependabot-omnibus@0.121.0
- pkg:gem/dependabot-omnibus@0.121.1
- pkg:gem/dependabot-omnibus@0.122.0
- pkg:gem/dependabot-omnibus@0.122.1
- pkg:gem/dependabot-omnibus@0.123.0
- pkg:gem/dependabot-omnibus@0.123.1
- pkg:gem/dependabot-omnibus@0.124.0
- pkg:gem/dependabot-omnibus@0.124.1
- pkg:gem/dependabot-omnibus@0.124.2
- pkg:gem/dependabot-omnibus@0.124.3
- pkg:gem/dependabot-omnibus@0.124.4
- pkg:gem/dependabot-omnibus@0.124.5
- pkg:gem/dependabot-omnibus@0.124.6
- pkg:gem/dependabot-omnibus@0.124.7
- pkg:gem/dependabot-omnibus@0.124.8
- pkg:gem/dependabot-omnibus@0.125.0
aliases:
- CVE-2020-26222
- GHSA-23f7-99jx-m54r
fixed_purl:
- pkg:gem/dependabot-common@0.125.1
- pkg:gem/dependabot-omnibus@0.125.1
references:
- id: 153035
  reference_id: ''
  url: https://github.com/dependabot/dependabot-core/commit/e089116abbe284425b976f7920e502b8e83a61b5
- id: 153034
  reference_id: ''
  url: https://github.com/dependabot/dependabot-core/pull/2727
- id: 153036
  reference_id: ''
  url: https://rubygems.org/gems/dependabot-common
- id: 153037
  reference_id: ''
  url: https://rubygems.org/gems/dependabot-omnibus
- id: 153038
  reference_id: CVE-2020-26222
  url: https://nvd.nist.gov/vuln/detail/CVE-2020-26222
- id: 153040
  reference_id: CVE-2020-26222.YML
  url: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/dependabot-common/CVE-2020-26222.yml
- id: 153039
  reference_id: CVE-2020-26222.YML
  url: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/dependabot-omnibus/CVE-2020-26222.yml
- id: 153041
  reference_id: GHSA-23f7-99jx-m54r
  url: https://github.com/advisories/GHSA-23f7-99jx-m54r
- id: 153033
  reference_id: GHSA-23f7-99jx-m54r
  url: https://github.com/dependabot/dependabot-core/security/advisories/GHSA-23f7-99jx-m54r
severities:
- id: 21857
  reference_id: 153041
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
- id: 21856
  reference_id: 153033
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: Remote code execution in dependabot-core branch names when cloning
vulnerability_id: VCID-psj2-fhrd-aaah
weaknesses: []
