vulnerability_id: VCID-g7nn-u2j4-aaae
aliases:
  - CVE-2021-39939
summary: An uncontrolled resource consumption vulnerability in GitLab Runner affecting all versions
  starting from 13.7 before 14.3.6, all versions starting from 14.4 before 14.4.4, all versions
  starting from 14.5 before 14.5.2, allows an attacker triggering a job with a specially crafted
  docker image to exhaust resources on runner manager
severities:
  - id: 558829
    reference_id: 896668
    scoring_system: cvssv2
    value: '4.0'
    scoring_elements: AV:N/AC:L/Au:S/C:N/I:N/A:P
  - id: 558827
    reference_id: 896668
    scoring_system: cvssv3
    value: '6.5'
    scoring_elements: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
references:
  - id: 896666
    url: https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-39939.json
    reference_id:
  - id: 896667
    url: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28630
    reference_id:
  - id: 536316
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*
    reference_id: cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*
  - id: 536317
    url: https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*
    reference_id: cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*
  - id: 896668
    url: https://nvd.nist.gov/vuln/detail/CVE-2021-39939
    reference_id: CVE-2021-39939
weaknesses: []
