affected_purls: []
aliases:
- CVE-2021-3429
fixed_purl:
- pkg:deb/debian/cloud-init@20.2-2~deb10u2?distro=sid
- pkg:deb/debian/cloud-init@20.4.1-2?distro=sid
- pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=sid
- pkg:deb/debian/cloud-init@22.4.2-1?distro=sid
references:
- id: 129868
  reference_id: '985540'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985540
severities: []
summary: When instructing cloud-init to set a random password for a new user account,
  versions before 21.2 would write that password to the world-readable log file /var/log/cloud-init-output.log.
  This could allow a local user to log in as another user.
vulnerability_id: VCID-mv1k-pt9y-aaan
weaknesses: []
