package: pkg:deb/debian/mate-settings-daemon
versions:
  - purl: pkg:deb/debian/mate-settings-daemon@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@0?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@0?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.16.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.16.2-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.20.4-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.20.4-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.20.4-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.20.4-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.24.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.24.1-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.24.1-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.24.1-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.26.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.26.0-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.26.0-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
  - purl: pkg:deb/debian/mate-settings-daemon@1.26.0-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-f72t-gc9a-aaar
