pacakge: pkg:deb/debian/system-config-printer
versions:
  - purl: pkg:deb/debian/system-config-printer@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
  - purl: pkg:deb/debian/system-config-printer@0?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
  - purl: pkg:deb/debian/system-config-printer@0?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
  - purl: pkg:deb/debian/system-config-printer@0?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
  - purl: pkg:deb/debian/system-config-printer@1.3.7-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.3.7-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.3.7-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.3.7-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.11-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.11-4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.11-4?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.11-4?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.14-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.14-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.14-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.14-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.16-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.16-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.16-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.16-1?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.18-1?distro=sid
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.7-3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
  - purl: pkg:deb/debian/system-config-printer@1.5.7-3?distro=stretch
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-3mhx-f75s-aaan
      - VCID-vu6v-5wz4-aaaf
