affected_purls:
- pkg:npm/%40mittwald/kubernetes@2.0.0
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.1
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.10
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.11
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.12
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.16
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.17
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.18
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.19
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.2
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.20
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.21
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.22
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.3
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.4
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.5
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.6
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.7
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.8
- pkg:npm/%40mittwald/kubernetes@2.0.0-beta.9
- pkg:npm/%40mittwald/kubernetes@2.1.0
- pkg:npm/%40mittwald/kubernetes@2.1.1
- pkg:npm/%40mittwald/kubernetes@2.1.2
- pkg:npm/%40mittwald/kubernetes@2.2.0
- pkg:npm/%40mittwald/kubernetes@2.3.0
- pkg:npm/%40mittwald/kubernetes@2.3.1
- pkg:npm/%40mittwald/kubernetes@2.3.2
- pkg:npm/%40mittwald/kubernetes@2.3.3
- pkg:npm/%40mittwald/kubernetes@2.3.4
- pkg:npm/%40mittwald/kubernetes@2.5.0
- pkg:npm/%40mittwald/kubernetes@2.5.1
- pkg:npm/%40mittwald/kubernetes@2.5.2
- pkg:npm/%40mittwald/kubernetes@2.6.0
- pkg:npm/%40mittwald/kubernetes@2.6.1
- pkg:npm/%40mittwald/kubernetes@3.0.0
- pkg:npm/%40mittwald/kubernetes@3.0.1
- pkg:npm/%40mittwald/kubernetes@3.0.2
- pkg:npm/%40mittwald/kubernetes@3.1.0
- pkg:npm/%40mittwald/kubernetes@3.2.0
- pkg:npm/%40mittwald/kubernetes@3.2.1
- pkg:npm/%40mittwald/kubernetes@3.2.2
- pkg:npm/%40mittwald/kubernetes@3.3.0
- pkg:npm/%40mittwald/kubernetes@3.3.5
- pkg:npm/%40mittwald/kubernetes@3.4.0
- pkg:npm/%40mittwald/kubernetes@3.4.1
- pkg:npm/%40mittwald/kubernetes@3.4.2
aliases:
- GHSA-g35x-j6jj-8g7j
fixed_purl:
- pkg:npm/%40mittwald/kubernetes@3.5.0
references:
- id: 131806
  reference_id: ''
  url: https://github.com/mittwald/node-kubernetes/commit/04f6809fd438417c343d541e57f76f0040e069cd
- id: 131807
  reference_id: ''
  url: https://github.com/mittwald/node-kubernetes/releases/tag/v3.5.0
- id: 131808
  reference_id: GHSA-g35x-j6jj-8g7j
  url: https://github.com/advisories/GHSA-g35x-j6jj-8g7j
- id: 131805
  reference_id: GHSA-g35x-j6jj-8g7j
  url: https://github.com/mittwald/node-kubernetes/security/advisories/GHSA-g35x-j6jj-8g7j
severities:
- id: 17706
  reference_id: 131808
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
- id: 17705
  reference_id: 131805
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: '@mittwald/kubernetes''s secret contents leaked via debug logging'
vulnerability_id: VCID-t3c2-69h8-aaam
weaknesses: []
