pacakge: pkg:deb/ubuntu/kconfig
versions:
  - purl: pkg:deb/ubuntu/kconfig@5.0.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.0.0-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.0.0-0ubuntu3
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.10.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.1.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.12.0-1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.13.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.13.0-1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.14.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.15.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.15.0-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.18.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.18.0-0ubuntu1.1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.2.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.22.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.24.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.26.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.28.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.30.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.3.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.31.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.33.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.34.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.35.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.36.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.37.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.38.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.40.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.4.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.41.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.42.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.43.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.44.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.44.0-0ubuntu1.1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.46.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.46.0-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.47.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.47.0-0ubuntu2
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.49.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.50.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.5.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.52.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.53.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.54.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.55.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.56.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.56.0-0ubuntu1.1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.57.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.58.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.59.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.60.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.60.0-0ubuntu2
    affected_by_vulnerabilities: []
    fixing_vulnerabilities:
      - VCID-ezms-uxg1-aaar
  - purl: pkg:deb/ubuntu/kconfig@5.6.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.7.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.8.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
  - purl: pkg:deb/ubuntu/kconfig@5.9.0-0ubuntu1
    affected_by_vulnerabilities:
      - VCID-ezms-uxg1-aaar
    fixing_vulnerabilities: []
